import {makeResponseWithLoading} from "./util/index.mjs";
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var g=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,m=ea&&self.name?.startsWith("em-pthread"),fa=Object.assign({},g),ha="",ia,ja;
if(da||ea)ea?ha=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ha=document.currentScript.src),_scriptName&&(ha=_scriptName),ha.startsWith("blob:")?ha="":ha=ha.slice(0,ha.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var ka=console.log.bind(console),p=console.error.bind(console);Object.assign(g,fa);fa=null;var q,la,ma=!1,na,oa,pa,qa,ra,sa,ta,ua,va,wa,xa,ya=!1,Aa=!1;function w(){q.buffer!=oa.buffer&&Ba();return oa}function x(){q.buffer!=oa.buffer&&Ba();return pa}function A(){q.buffer!=oa.buffer&&Ba();return qa}function Ca(){q.buffer!=oa.buffer&&Ba();return ra}function C(){q.buffer!=oa.buffer&&Ba();return sa}function F(){q.buffer!=oa.buffer&&Ba();return ta}function Da(){q.buffer!=oa.buffer&&Ba();return ua}
function Fa(){q.buffer!=oa.buffer&&Ba();return xa}
if(m){var Ga,Ha=!1;p=function(...b){console.error(b.join(" "))};self.alert=function(...b){postMessage({If:"alert",text:b.join(" "),Dh:Ia()})};self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.If;if("load"===d){let e=[];self.onmessage=f=>e.push(f);self.startWorker=()=>{postMessage({If:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.nh)if(!g[f]||g[f].proxy)g[f]=(...h)=>{postMessage({If:"callHandler",mh:f,fh:h})},"print"==f&&(ka=g[f]),"printErr"==
f&&(p=g[f]);q=c.Fh;Ba();Ga(c.Gh)}else if("run"===d){Ja(c.Kf);Ka(c.Kf,0,0,1,0,0);La(c);Ma();Na(c.Kf);Ha||(Oa(),Ha=!0);try{Pa(c.Bh,c.hg)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?Ha&&Qa():d&&(p(`worker: received unknown command ${d}`),p(c)))}catch(e){throw Ra(),e;}}self.onmessage=a}
function Ba(){var a=q.buffer;oa=new Int8Array(a);qa=new Int16Array(a);pa=new Uint8Array(a);ra=new Uint16Array(a);sa=new Int32Array(a);ta=new Uint32Array(a);ua=new Float32Array(a);xa=new Float64Array(a);va=new BigInt64Array(a);wa=new BigUint64Array(a)}m||(q=new WebAssembly.Memory({initial:2048,maximum:(/iPad|iPhone|iPod/.test("undefined"!==typeof navigator?navigator.userAgent:"")?536870912:2147483648)/65536,shared:!0}),Ba());function Sa(){ya=!0;m?startWorker(g):G.$c()}var Ta=0,Ua=null;
function Va(){Ta--;if(0==Ta&&Ua){var a=Ua;Ua=null;a()}}function Wa(a){a="Aborted("+a+")";p(a);ma=!0;a+=". Build with -sASSERTIONS for more info.";ya&&Xa();a=new WebAssembly.RuntimeError(a);ba(a);throw a;}var Ya;async function Za(a){try{var b=await ia(a);return new Uint8Array(b)}catch{}if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function $a(a,b){try{var c=await Za(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),Wa(d)}}async function ab(a){var b=Ya;if("function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(makeResponseWithLoading(c),a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return $a(b,a)}
function bb(){cb={Ya:db,Ub:eb,fc:fb,J:gb,xc:hb,cc:ib,ec:jb,Aa:kb,vc:lb,nc:mb,uc:nb,ab:ob,dc:pb,ac:qb,wc:rb,bc:sb,Ac:tb,m:ub,Va:vb,Rb:wb,Pb:xb,q:yb,d:zb,Ua:Ab,g:Bb,R:Cb,u:Db,Qb:Eb,ya:Fb,C:Gb,e:Hb,Sb:Ib,qc:Jb,_b:Kb,gc:Lb,Wb:Mb,_a:Nb,pc:Na,yc:Ob,j:Pb,Ia:Qb,ea:Rb,c:Sb,Tb,U:Ub,h:Vb,da:Wb,oa:Xb,Xa:Yb,i:Zb,f:$b,n:ac,jc:bc,kc:cc,lc:dc,hc:ec,ic:fc,Xb:gc,mc:hc,_c:ic,xb:jc,Wc:kc,Xc:lc,yb:mc,zb:nc,vb:oc,wb:pc,Yc:qc,sb:rc,Zc:sc,ja:tc,La:uc,zc:vc,Ra:wc,Vc:xc,t:yc,tb:zc,Gb:Ac,$a:Bc,bb:Cc,Dc,Wa:Ec,Bc:Fc,qb:Gc,Ta:Hc,
Sa:Ic,wa:Jc,$b:Kc,b:Lc,Hb:Mc,Ib:Nc,Pa:Oc,ia:Pc,Ob:Qc,Zb:Rc,xa:Sc,eb:Tc,db:Uc,Za:Vc,lb:Wc,jb:Xc,kb:Yc,hb:Zc,gb:$c,ib:ad,fb:bd,Cc:cd,Ec:dd,Fc:ed,mb:fd,Nb:gd,sc:hd,tc:jd,Ba:kd,fa:ld,rc:md,cb:nd,oc:od,za:pd,Tc:qd,Mb:rd,X:sd,Kc:td,p:ud,x:vd,O:wd,y:xd,k:yd,Ka:zd,ga:Ad,Rc:Bd,H:Cd,Ga:Dd,Cb:Ed,ka:Fd,Z:Gd,Ma:Hd,Na:Id,Nc:Jd,Lc:Kd,Pc:Ld,va:Md,w:Nd,na:Od,nb:Pd,aa:Qd,Fa:Rd,Q:Sd,F:Td,T:Ud,ca:Vd,Gc:Wd,A:Xd,G:Yd,Db:Zd,Ha:$d,o:ae,E:be,N:ce,sa:de,ua:ee,L:fe,ma:ge,_:he,V:ie,I:je,Sc:ke,Hc:le,Da:me,ta:ne,W:oe,S:pe,Ic:qe,
ob:re,Mc:se,pb:te,l:ue,z:ve,ba:we,Eb:xe,Ca:ye,Fb:ze,qa:Ae,$:Be,Jc:Ce,la:De,Oa:Ee,Bb:Fe,Ab:Ge,ra:Ie,rb:Je,Ja:Ke,Oc:Le,P:Me,s:Ne,ha:Oe,B:Pe,K:Qe,Ea:Re,pa:Se,Qc:Te,Y:Ue,v:Ve,r:We,D:Xe,M:Ye,Lb:Ze,a:q,Vb:$e,Yb:af,Jb:bf,ub:cf,Kb:df,Qa:ef,Uc:ff};return{a:cb}}
var hf={15724188:(a,b,c,d)=>{if("undefined"==typeof g||!g.dh)return 1;a=H(a>>>0);a.startsWith("./")&&(a=a.substring(2));a=g.dh.get(a);if(!a)return 2;b>>>=0;c>>>=0;d>>>=0;if(b+c>a.byteLength)return 3;try{return x().set(a.subarray(b,b+c),d),0}catch{return 4}},15724689:()=>g.MxCaptureRunning?1:0,15724736:a=>{a=H(a).replace(/^#/,"");const b=document.getElementById(a),c=document.createElement("canvas");c.width=b.width;c.height=b.height;c.style=b.style;b.replaceWith(c);c.id=a},15725049:()=>/Mobile|Android|iPhone|iPad/i.test(navigator.userAgent),
15725117:()=>{let a=!0,b=null,c=0;const d=f=>{(null===b||f>c)&&0<f&&(null!==b&&I(b),b=K(f),c=f)},e=self.onmessage;self.onmessage=f=>{if("MxStartFrameProcessing"===f.data.cmd)a=!0;else if("MxFinishFrameProcessing"===f.data.cmd)a=!1,null!==b&&(I(b),b=null,c=0);else if("MxProcessFrame"===f.data.cmd){if(a){var h=f.data.frame,k=f.data.format,l=f.data.width,n=f.data.height,r=f.data.timestamp,v=f.data.facing_user,t=f.data.full_frame_processing;f=f.data.device_id;if(h instanceof ImageData)h=h.data,d(h.byteLength),
x().set(h,b),g._ingestCameraFrame(b,h.byteLength,k,l,n,r,v,t,f);else{var y={x:0,y:0};y.width=l;y.height=n;y={rect:y};var E=h.allocationSize(y);d(E);E=x().subarray(b,b+E);h.copyTo(E,y);g._ingestCameraFrame(b,E.byteLength,k,l,n,r,v,t,f);h.close()}}}else e(f)}},15727011:a=>{const b=a.toString();g.MxStartFrameProcessing=()=>{gf[b].postMessage({cmd:"MxStartFrameProcessing"})};g.MxFinishFrameProcessing=()=>{gf[b].postMessage({cmd:"MxFinishFrameProcessing"})};g.MxDispatchFrameToThread=(c,d,e,f,h,k,l,n)=>
{gf[b].postMessage({cmd:"MxProcessFrame",frame:c,format:d,width:e,height:f,timestamp:h,facing_user:k,full_frame_processing:l,device_id:n},[c instanceof ImageData?c.data.buffer:c])}},15727815:()=>{g.MxStartFrameProcessing&&g.MxStartFrameProcessing()},15727897:()=>{g.MxFinishFrameProcessing&&g.MxFinishFrameProcessing()},15727981:()=>{window.MxClosePreloadDisplay()},15728020:a=>{a=H(a);window.MxUpdatePreloadDisplay(a)},15728095:a=>{const b=H(a),c=performance.now(),d=()=>window.MxUpdatePreloadDisplay(b,
c);navigator.permissions.query({name:"camera"}).then(e=>{"prompt"==e.state&&d()}).catch(()=>{setTimeout(d,1E3)})},15728526:a=>{console.log(H(a))},15728561:(a,b)=>{fetch("https://telemetry.shen.ai/v1/traces",{method:"POST",body:H(a),headers:{"Content-Type":"application/json","X-Shen-Telemetry-Transport":"http"},keepalive:b})}};function ic(){window.Df||(window.Df=function(){g._handlePagehide()},window.addEventListener("pagehide",window.Df))}
function cf(){window.Df&&(window.removeEventListener("pagehide",window.Df),delete window.Df)}function gd(){(void 0===g.MxCaptureRunning?navigator.mediaDevices.getUserMedia({video:!0}):Promise.resolve()).then(()=>{navigator.mediaDevices.enumerateDevices().then(a=>{g.MxVideoDevices=a.filter(b=>"videoinput"==b.kind).map(b=>({id:b.deviceId??"",label:b.label??""}));g._onVideoDevicesEnumerated()}).catch(()=>{g._onVideoDevicesEnumerationError()})}).catch(()=>{g._onVideoDevicesEnumerationError()})}
function rd(){const a=JSON.stringify(g.MxVideoDevices),b=jf(a)+1,c=K(b);M(a,c,b);return c}
function Ze(a,b,c){function d(){navigator.mediaDevices.getUserMedia(v).then(t=>{const y=t.getVideoTracks()[0];"undefined"!==typeof MediaStreamTrackProcessor?f(new MediaStreamTrackProcessor({track:y}),y):h(t,y);g.MxVideoTrack=y}).catch(t=>{g.MxCaptureRunning=void 0;g.MxVideoTrack=void 0;g._onCameraInitializationError();console.error("Camera initialization error:",t)})}function e(){void 0==g.MxCaptureRunning?(g.MxCaptureRunning=!1,d()):setTimeout(e,100)}function f(t,y){g.MxCaptureRunning=!0;g._onCameraInitialized();
const E=t.readable.getReader(),L=async()=>{try{if(g.MxCaptureRunning){const B=await E.read();if(B.value){var z=B.value;g.MxDispatchFrameToThread?g.MxDispatchFrameToThread(z,l[z.format]??l.unsupported,z.codedWidth,z.codedHeight,BigInt(z.timestamp),a,b,r):z.close();L()}else setTimeout(L,1E3/30)}else E.releaseLock(),y.stop(),g.MxCaptureRunning=void 0,g.MxVideoTrack=void 0}catch(B){console.error("Error reading frame",B)}};L()}function h(t,y){const E=new OffscreenCanvas(1,1),L=E.getContext("2d",{willReadFrequently:!0}),
z=document.createElement("video");z.setAttribute("id","shen-camera-proxy");z.setAttribute("playsinline","");z.setAttribute("muted","");z.setAttribute("disablepictureinpicture","");z.style.position="absolute";z.style.top="0";z.style.left="0";z.style.width="1px";z.style.height="1px";document.body.appendChild(z);let B=null;z.onloadedmetadata=()=>{var N=z.videoWidth,u=z.videoHeight;let O=N,D=u,P={x:0,y:0};if(!b){const J=O/D;.6>J?(D=Math.floor(O/k),D-=D&1,P.y=Math.floor((u-D)/2)):.75<J&&(O=Math.floor(D*
k),O-=O&1,P.x=Math.floor((N-O)/2))}B={width:O,height:D,offset:P};E.width=B.width;E.height=B.height;z.play()};z.onplay=()=>{g.MxCaptureRunning=!0;g._onCameraInitialized();const N=1E3/30,u=()=>{if(g.MxCaptureRunning){const O=performance.now();if(B){L.drawImage(z,B.offset.x,B.offset.y,B.width,B.height,0,0,B.width,B.height);try{const D=L.getImageData(0,0,B.width,B.height),P=Math.round(1E3*O);g.MxDispatchFrameToThread&&g.MxDispatchFrameToThread(D,l.RGBA,B.width,B.height,BigInt(P),a,b,r)}catch(D){console.error("Error capturing frame:",
D)}}setTimeout(u,Math.max(0,N-(performance.now()-O)))}else z.pause(),y.stop(),z.parentNode.removeChild(z),g.MxCaptureRunning=void 0};u()};z.srcObject=t}const k=480/720,l={unsupported:0,I420:1,I420A:2,RGBA:3,RGBX:4,BGRA:5,BGRX:6,NV12:7},n=H(c),r=(()=>{if(""==n)return-1;void 0===g.MxDeviceIdStrToIntMap&&(g.MxDeviceIdStrToIntMap=new Map);let t=g.MxDeviceIdStrToIntMap.get(n);void 0===t&&(t=g.MxDeviceIdStrToIntMap.size,g.MxDeviceIdStrToIntMap.set(n,t));return t})(),v={video:(()=>{if(""!=n)return{deviceId:{exact:n}};
const t=/Mobile|Android|iPhone|iPad/i.test(navigator.userAgent),y={ideal:720,min:640},E={ideal:t?1/k:k};return{frameRate:{ideal:30},facingMode:{ideal:a?"user":"environment"},aspectRatio:b?void 0:E,width:t?y:void 0,height:t?void 0:y,resizeMode:t?void 0:{exact:"none"}}})()};e()}function wc(){g.MxCaptureRunning&&(g.MxCaptureRunning=!1)}
function ef(a){const b=g.MxVideoTrack;if(b&&"undefined"!==typeof b.getCapabilities){const c=b.getCapabilities();b.getSettings();const d={advanced:[]};c.whiteBalanceMode&&d.advanced.push({whiteBalanceMode:a?"manual":"continuous"});0<d.advanced.length&&b.applyConstraints(d).catch(()=>{})}}function df(){"wakeLock"in navigator&&navigator.wakeLock.request("screen").then(a=>g.MxWakeLock=a).catch(()=>{})}function bf(){g.MxWakeLock&&g.MxWakeLock.release().then(()=>g.MxWakeLock=null).catch(()=>{})}
function xc(){navigator.bluetooth?(console.log("[PolarH10] Starting doScan... requesting device with name 'Polar H10'"),g.polar||(g.polar={device:null,server:null,pmdService:null,controlChar:null,dataChar:null}),navigator.bluetooth.requestDevice({filters:[{namePrefix:"Polar H10"}],optionalServices:["fb005c80-02e7-f387-1cad-8acd2d8df0c8"]}).then(a=>{console.log("[PolarH10] Device chosen:",a);g.polar.device=a;return a.gatt.connect()}).then(a=>{console.log("[PolarH10] GATT connected");g.polar.server=
a;return a.getPrimaryService("fb005c80-02e7-f387-1cad-8acd2d8df0c8")}).then(a=>{console.log("[PolarH10] Found PMD service");g.polar.pmdService=a;return Promise.all([a.getCharacteristic("fb005c81-02e7-f387-1cad-8acd2d8df0c8"),a.getCharacteristic("fb005c82-02e7-f387-1cad-8acd2d8df0c8")])}).then(a=>{const b=a[0];a=a[1];console.log("[PolarH10] Found control & data characteristics");g.polar.controlChar=b;g.polar.dataChar=a;return Promise.all([b.startNotifications(),a.startNotifications()])}).then(()=>
{console.log("[PolarH10] Notifications started");const a=g.polar.dataChar;g.polar.controlChar.addEventListener("characteristicvaluechanged",b=>{b=new Uint8Array(b.target.value.buffer);const c=g._malloc(b.length);x().set(b,c);g._onBleControlNotification(c,b.length);g._free(c)});a.addEventListener("characteristicvaluechanged",b=>{b=new Uint8Array(b.target.value.buffer);const c=g._malloc(b.length);x().set(b,c);g._onBleDataNotification(c,b.length);g._free(c)});g._onBleDeviceReady()}).catch(a=>{console.error("[PolarH10] doScan() error:",
a)})):console.error("Web Bluetooth not supported by this browser")}function ff(a,b){if(g.polar&&g.polar.controlChar){var c=new Uint8Array(b);for(let d=0;d<b;d++)c[d]=x()[a+d];g.polar.controlChar.writeValue(c).then(()=>{console.log("[PolarH10] ControlChar write success")}).catch(d=>{console.error("[PolarH10] ControlChar write error:",d)})}else console.warn("[PolarH10] No polar.controlChar to write to")}
function qd(){var a=navigator.userAgent,b="unknown",c="unknown",d=!0,e=navigator.language;-1!==a.indexOf("Chrome")?(b="Chrome",c=a.substr(a.indexOf("Chrome")+7,12)):-1!==a.indexOf("Safari")?(b="Safari",c=a.substr(a.indexOf("Version")+8,8)):-1!==a.indexOf("Firefox")?(b="Firefox",c=a.substr(a.indexOf("Firefox")+8,12)):-1!==a.indexOf("Opera")||-1!==a.indexOf("OPR")?(b="Opera",c=a.substr(a.indexOf("Version")+8,12)):-1!==a.indexOf("Edge")&&(b="Edge",c=a.substr(a.indexOf("Edge")+5,12));-1!==a.indexOf("Android")?
a="Android":-1!==a.indexOf("iPhone")||-1!==a.indexOf("iPad")||-1!==a.indexOf("iPod")?a="iOS":-1!==a.indexOf("Mobile")?a="Unknown (mobile)":(a=-1!==a.indexOf("Mac OS")?"Mac OS":-1!==a.indexOf("Windows")?"Windows":-1!==a.indexOf("Linux")?"Linux":"Unknown (desktop)",d=!1);b=JSON.stringify({browser:b,version:c,os:a,is_mobile:d,language:e});c=jf(b)+1;d=K(c);M(b,d,c);return d}class kf{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var lf=a=>{a.terminate();a.onmessage=()=>{}},mf=[],qf=a=>{if(0==nf.length){var b=new Worker(new URL("shenai_sdk.mjs",import.meta.url),{type:"module",name:"em-pthread"});nf.push(b);of()}b=nf.pop();if(!b)return 6;pf.push(b);gf[a.Kf]=b;b.Kf=a.Kf;var c={If:"run",Bh:a.Ah,hg:a.hg,Kf:a.Kf};c.Rf=a.Rf;c.yg=a.yg;b.postMessage(c,a.Zg);return 0},Q=0,R=(a,b,...c)=>{for(var d=2*c.length,e=rf(),f=sf(8*d),h=f>>3,k=0;k<c.length;k++){var l=c[k];"bigint"==typeof l?(va[h+2*k]=1n,va[h+2*k+1]=l):(va[h+2*k]=
0n,Fa()[h+2*k+1]=l)}a=tf(a,0,d,f,b);uf(e);return a};function $e(a){if(m)return R(0,1,a);na=a;0<Q||(vf(),ma=!0);throw new kf(a);}var wf=a=>{if(!(a instanceof kf||"unwind"==a))throw a;};function xf(a){if(m)return R(1,0,a);kd(a)}
var kd=a=>{na=a;if(m)throw xf(a),"unwind";if(!(0<Q||m)){yf();for(var b=zf;0<b.length;)b.shift()(g);Af(0);Bf[1].length&&Cf(1,10);Bf[2].length&&Cf(2,10);vf();Aa=!0}$e(a)},nf=[],pf=[],Ef=[],gf={},vf=()=>{for(var a of pf)lf(a);for(a of nf)lf(a);nf=[];pf=[];gf={}},Gf=a=>{var b=a.Kf;delete gf[b];nf.push(a);pf.splice(pf.indexOf(a),1);a.Kf=0;Ff(b)};function La(a){"undefined"!=typeof Hf&&(Object.assign(If,a.yg),!g.canvas&&a.Rf&&If[a.Rf]&&(g.canvas=If[a.Rf].Jf,g.canvas.id=a.Rf))}
function Ma(){Ef.forEach(a=>a())}
var of=()=>{var a=nf[0];new Promise(b=>{a.onmessage=f=>{f=f.data;var h=f.If;if(f.qg&&f.qg!=Ia()){var k=gf[f.qg];k?k.postMessage(f,f.Zg):p(`Internal error! Worker sent a message "${h}" to target pthread ${f.qg}, but that thread no longer exists!`)}else if("checkMailbox"===h)Qa();else if("spawnThread"===h)qf(f);else if("cleanupThread"===h)Gf(gf[f.Ch]);else if("loaded"===h)a.loaded=!0,b(a);else if("alert"===h)alert(`Thread ${f.Dh}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===
h)g[f.mh](...f.fh);else h&&p(`worker sent an unknown command ${h}`)};a.onerror=f=>{p(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=[],e;for(e of d)g.propertyIsEnumerable(e)&&c.push(e);a.postMessage({If:"load",nh:c,Fh:q,Gh:la})})},Jf,Ja=a=>{Ba();var b=F()[a+52>>2];a=F()[a+56>>2];Kf(b,b-a);uf(b)},Lf=[],Mf,S=a=>{var b=Lf[a];b||(a>=Lf.length&&(Lf.length=a+1),Lf[a]=b=Mf.get(a));return b},Pa=(a,b)=>{Q=0;a=S(a)(b);0<Q?na=a:Nf(a)},Of="undefined"!=typeof TextDecoder?
new TextDecoder:void 0,Pf=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Of)return Of.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
H=(a,b)=>a?Pf(x(),a,b):"",db=(a,b,c,d)=>Wa(`Assertion failed: ${H(a)}, at: `+[b?H(b):"unknown filename",c,d?H(d):"unknown function"]),eb=(a,b)=>S(a)(b);function Qf(a,b,c,d){return m?R(2,1,a,b,c,d):fb(a,b,c,d)}
var fb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[],f=0,h=b?F()[b+40>>2]:0;h=(h=4294967295==h?"#canvas":H(h).trim())?h.split(","):[];var k={},l=g.canvas?.id||"";for(n of h){var n=n.trim();try{if("#canvas"==n){if(!g.canvas){p(`pthread_create: could not find canvas with ID "${n}" to transfer to thread!`);f=28;break}n=g.canvas.id}if(If[n]){var r=If[n];If[n]=null;g.canvas instanceof OffscreenCanvas&&n===g.canvas.id&&(g.canvas=null)}else if(!m){var v=g.canvas&&g.canvas.id===n?
g.canvas:document.querySelector(n);if(!v){p(`pthread_create: could not find canvas with ID "${n}" to transfer to thread!`);f=28;break}if(v.Wf){p(`pthread_create: cannot transfer canvas with ID "${n}" to thread, since the current thread does not have control over it!`);f=63;break}if(v.transferControlToOffscreen)v.yf||(v.yf=K(12),C()[v.yf>>2]=v.width,C()[v.yf+4>>2]=v.height,F()[v.yf+8>>2]=0),r={Jf:v.transferControlToOffscreen(),yf:v.yf,id:v.id},v.Wf=!0;else return p(`pthread_create: cannot transfer control of canvas "${n}" to pthread, because current browser does not support OffscreenCanvas!`),
p("pthread_create: Build with -sOFFSCREEN_FRAMEBUFFER to enable fallback proxying of GL commands from pthread to main thread."),52}r&&(e.push(r.Jf),k[r.id]=r)}catch(t){return p(`pthread_create: failed to transfer control of canvas "${n}" to OffscreenCanvas! Error: ${t}`),28}}if(m&&(0===e.length||f))return Qf(a,b,c,d);if(f)return f;for(v of Object.values(k))F()[v.yf+8>>2]=a;a={Ah:c,Kf:a,hg:d,Rf:l,yg:k,Zg:e};return m?(a.If="spawnThread",postMessage(a,e),0):qf(a)};
function gb(a,b,c){return m?R(3,1,a,b,c):0}function hb(a,b){if(m)return R(4,1,a,b)}
var jf=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},M=(a,b,c)=>{var d=x();if(0<c){var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=
128|h>>6&63}d[b++]=128|h&63}}d[b]=0;a=b-e}else a=0;return a};function ib(a,b){if(m)return R(5,1,a,b)}function jb(a,b,c){if(m)return R(6,1,a,b,c)}function kb(a,b,c){return m?R(7,1,a,b,c):0}function lb(a,b){if(m)return R(8,1,a,b)}function mb(a,b,c){if(m)return R(9,1,a,b,c)}function nb(a,b,c,d){if(m)return R(10,1,a,b,c,d)}function ob(a,b,c,d){if(m)return R(11,1,a,b,c,d)}function pb(a,b,c,d){if(m)return R(12,1,a,b,c,d)}function qb(a){if(m)return R(13,1,a)}function rb(a,b){if(m)return R(14,1,a,b)}
function sb(a,b,c){if(m)return R(15,1,a,b,c)}var tb=()=>Wa(""),Rf={},Sf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Tf(a){return this.fromWireType(F()[a>>2])}
var Uf={},Vf={},Wf={},Xf,Zf=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Xf("Mismatched type converter count");for(var l=0;l<a.length;++l)Yf(a[l],k[l])}a.forEach(k=>Wf[k]=b);var e=Array(b.length),f=[],h=0;b.forEach((k,l)=>{Vf.hasOwnProperty(k)?e[l]=Vf[k]:(f.push(k),Uf.hasOwnProperty(k)||(Uf[k]=[]),Uf[k].push(()=>{e[l]=Vf[k];++h;h===f.length&&d(e)}))});0===f.length&&d(e)},ub=a=>{var b=Rf[a];delete Rf[a];var c=b.sh,d=b.th,e=b.Pg,f=e.map(h=>h.lh).concat(e.map(h=>h.yh));Zf([a],f,h=>
{var k={};e.forEach((l,n)=>{var r=h[n],v=l.jh,t=l.kh,y=h[n+e.length],E=l.xh,L=l.zh;k[l.ih]={read:z=>r.fromWireType(v(t,z)),write:(z,B)=>{var N=[];E(L,z,y.toWireType(N,B));Sf(N)}}});return[{name:b.name,fromWireType:l=>{var n={},r;for(r in k)n[r]=k[r].read(l);d(l);return n},toWireType:(l,n)=>{for(var r in k)if(!(r in n))throw new TypeError(`Missing field: "${r}"`);var v=c();for(r in k)k[r].write(v,n[r]);null!==l&&l.push(d,v);return v},Ff:$f,readValueFromPointer:Tf,Cf:d}]})},ag,T=a=>{for(var b="";x()[a];)b+=
ag[x()[a++]];return b},U,bg=a=>{throw new U(a);};function cg(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(Vf.hasOwnProperty(a)){if(c.oh)return;throw new U(`Cannot register type '${d}' twice`);}Vf[a]=b;delete Wf[a];Uf.hasOwnProperty(a)&&(b=Uf[a],delete Uf[a],b.forEach(e=>e()))}function Yf(a,b,c={}){return cg(a,b,c)}
var dg=(a,b,c)=>{switch(b){case 1:return c?d=>w()[d]:d=>x()[d];case 2:return c?d=>A()[d>>1]:d=>Ca()[d>>1];case 4:return c?d=>C()[d>>2]:d=>F()[d>>2];case 8:return c?d=>va[d>>3]:d=>wa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},vb=(a,b,c)=>{b=T(b);Yf(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw null===e?e="null":(d=typeof e,e="object"===d||"array"===d||"function"===d?e.toString():""+e),new TypeError(`Cannot convert "${e}" to ${this.name}`);
"number"==typeof e&&(e=BigInt(e));return e},Ff:$f,readValueFromPointer:dg(b,c,-1==b.indexOf("u")),Cf:null})},$f=8,wb=(a,b,c,d)=>{b=T(b);Yf(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},Ff:$f,readValueFromPointer:function(e){return this.fromWireType(x()[e])},Cf:null})},eg=[],fg=[],Sb=a=>{9<a&&0===--fg[a+1]&&(fg[a]=void 0,eg.push(a))},gg=a=>{if(!a)throw new U("Cannot use deleted val. handle = "+a);return fg[a]},hg=a=>{switch(a){case void 0:return 2;case null:return 4;
case !0:return 6;case !1:return 8;default:const b=eg.pop()||fg.length;fg[b]=a;fg[b+1]=1;return b}},ig={name:"emscripten::val",fromWireType:a=>{var b=gg(a);Sb(a);return b},toWireType:(a,b)=>hg(b),Ff:$f,readValueFromPointer:Tf,Cf:null},xb=a=>Yf(a,ig),jg=(a,b)=>{if(void 0===g[a].Hf){var c=g[a];g[a]=function(...d){if(!g[a].Hf.hasOwnProperty(d.length))throw new U(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${g[a].Hf})!`);return g[a].Hf[d.length].apply(this,
d)};g[a].Hf=[];g[a].Hf[c.Jg]=c}},kg=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].Hf&&void 0!==g[a].Hf[c])throw new U(`Cannot register public name '${a}' twice`);jg(a,a);if(g[a].Hf.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);g[a].Hf[c]=b}else g[a]=b,g[a].Jg=c},lg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.fromWireType(w()[d])}:function(d){return this.fromWireType(x()[d])};case 2:return c?
function(d){return this.fromWireType(A()[d>>1])}:function(d){return this.fromWireType(Ca()[d>>1])};case 4:return c?function(d){return this.fromWireType(C()[d>>2])}:function(d){return this.fromWireType(F()[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},yb=(a,b,c,d)=>{function e(){}b=T(b);e.values={};Yf(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:(f,h)=>h.value,Ff:$f,readValueFromPointer:lg(b,c,d),Cf:null});kg(b,e)},mg=
(a,b)=>Object.defineProperty(b,"name",{value:a}),og=a=>{a=ng(a);var b=T(a);I(a);return b},pg=(a,b)=>{var c=Vf[a];if(void 0===c)throw a=`${b} has unknown type ${og(a)}`,new U(a);return c},zb=(a,b,c)=>{var d=pg(a,"enum");b=T(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:mg(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},qg=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(Da()[c>>2])};case 8:return function(c){return this.fromWireType(Fa()[c>>
3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ab=(a,b,c)=>{b=T(b);Yf(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,Ff:$f,readValueFromPointer:qg(b,c),Cf:null})};function rg(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Cf)return!0;return!1}
function sg(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=mg(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var tg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F()[b+4*d>>2]);return c},ug=(a,b)=>{a=T(a);var c=S(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c},vg,wg=(a,b)=>{function c(f){e[f]||Vf[f]||(Wf[f]?Wf[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new vg(`${a}: `+d.map(og).join([", "]));},xg=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Bb=(a,b,c,d,e,f,h)=>{var k=tg(b,c);a=T(a);a=xg(a);e=ug(d,e);kg(a,function(){wg(`Cannot call ${a} due to unbound types`,
k)},b-1);Zf([],k,l=>{var n=a;var r=a;l=[l[0],null].concat(l.slice(1));var v=e,t=l.length;if(2>t)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var y=null!==l[1]&&!1,E=rg(l),L="void"!==l[0].name;v=[r,bg,v,f,Sf,l[0],l[1]];for(var z=0;z<t-2;++z)v.push(l[z+2]);if(!E)for(z=y?1:2;z<l.length;++z)null!==l[z].Cf&&v.push(l[z].Cf);E=rg(l);z=l.length-2;var B=[],N=["fn"];y&&N.push("thisWired");for(t=0;t<z;++t)B.push(`arg${t}`),N.push(`arg${t}Wired`);B=B.join(",");
N=N.join(",");B=`return function (${B}) {\n`;E&&(B+="var destructors = [];\n");var u=E?"destructors":"null",O="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");y&&(B+=`var thisWired = classParam['toWireType'](${u}, this);\n`);for(t=0;t<z;++t)B+=`var arg${t}Wired = argType${t}['toWireType'](${u}, arg${t});\n`,O.push(`argType${t}`);B+=(L||h?"var rv = ":"")+`invoker(${N});\n`;if(E)B+="runDestructors(destructors);\n";else for(t=y?1:2;t<l.length;++t)y=1===t?"thisWired":
"arg"+(t-2)+"Wired",null!==l[t].Cf&&(B+=`${y}_dtor(${y});\n`,O.push(`${y}_dtor`));L&&(B+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [D,P]=[O,B+"}\n"];D.push(P);l=sg(D)(...v);r=mg(r,l);l=b-1;if(!g.hasOwnProperty(n))throw new Xf("Replacing nonexistent public symbol");void 0!==g[n].Hf&&void 0!==l?g[n].Hf[l]=r:(g[n]=r,g[n].Jg=l);return[]})},Cb=(a,b,c,d,e)=>{b=T(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var f=32-8*c;e=k=>k<<f>>>f}var h=b.includes("unsigned")?function(k,l){return l>>>
0}:function(k,l){return l};Yf(a,{name:b,fromWireType:e,toWireType:h,Ff:$f,readValueFromPointer:dg(b,c,0!==d),Cf:null})},Db=(a,b,c)=>{function d(f){var h=F()[f>>2];f=F()[f+4>>2];return new e(w().buffer,f,h)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=T(c);Yf(a,{name:c,fromWireType:d,Ff:$f,readValueFromPointer:d},{oh:!0})},Eb=(a,b)=>{b=T(b);Yf(a,{name:b,fromWireType:function(c){for(var d=F()[c>>2],e=c+4,f,h=e,
k=0;k<=d;++k){var l=e+k;if(k==d||0==x()[l])h=H(h,l-h),void 0===f?f=h:(f+=String.fromCharCode(0),f+=h),h=l+1}I(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||d instanceof Uint8Array||d instanceof Uint8ClampedArray||d instanceof Int8Array))throw new U("Cannot pass non-string to std::string");var f=e?jf(d):d.length;var h=K(4+f+1),k=h+4;F()[h>>2]=f;if(e)M(d,k,f+1);else if(e)for(e=0;e<f;++e){var l=d.charCodeAt(e);if(255<l)throw I(h),
new U("String has UTF-16 code units that do not fit in 8 bits");x()[k+e]=l}else for(e=0;e<f;++e)x()[k+e]=d[e];null!==c&&c.push(I,h);return h},Ff:$f,readValueFromPointer:Tf,Cf(c){I(c)}})},yg="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,zg=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&Ca()[c];)++c;c<<=1;if(32<c-a&&yg)return yg.decode(x().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var e=A()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Ag=(a,b,c)=>{c??=2147483647;if(2>
c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);A()[b>>1]=f;b+=2}A()[b>>1]=0;return b-d},Bg=a=>2*a.length,Cg=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=C()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Dg=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+
((f&1023)<<10)|h&1023}C()[b>>2]=f;b+=4;if(b+4>c)break}C()[b>>2]=0;return b-d},Eg=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Fb=(a,b,c)=>{c=T(c);if(2===b){var d=zg;var e=Ag;var f=Bg;var h=k=>Ca()[k>>1]}else 4===b&&(d=Cg,e=Dg,f=Eg,h=k=>F()[k>>2]);Yf(a,{name:c,fromWireType:k=>{for(var l=F()[k>>2],n,r=k+4,v=0;v<=l;++v){var t=k+4+v*b;if(v==l||0==h(t))r=d(r,t-r),void 0===n?n=r:(n+=String.fromCharCode(0),n+=r),r=t+b}I(k);return n},toWireType:(k,l)=>{if("string"!=
typeof l)throw new U(`Cannot pass non-string to C++ string type ${c}`);var n=f(l),r=K(4+n+b);F()[r>>2]=n/b;e(l,r+4,n+b);null!==k&&k.push(I,r);return r},Ff:$f,readValueFromPointer:Tf,Cf(k){I(k)}})},Gb=(a,b,c,d,e,f)=>{Rf[a]={name:T(b),sh:ug(c,d),th:ug(e,f),Pg:[]}},Hb=(a,b,c,d,e,f,h,k,l,n)=>{Rf[a].Pg.push({ih:T(b),lh:c,jh:ug(d,e),kh:f,yh:h,xh:ug(k,l),zh:n})},Ib=(a,b)=>{b=T(b);Yf(a,{qh:!0,name:b,Ff:0,fromWireType:()=>{},toWireType:()=>{}})},Jb=a=>{Ka(a,!ea,1,!da,2097152,!1);Ma()},Fg=()=>{if(!(Aa||0<Q))try{m?
Nf(na):kd(na)}catch(a){wf(a)}},Gg=a=>{if(!Aa&&!ma)try{a(),Fg()}catch(b){wf(b)}},Na=a=>{"function"===typeof Atomics.Eh&&(Atomics.Eh(C(),a>>2,a).value.then(Qa),a+=128,Atomics.store(C(),a>>2,1))},Qa=()=>{var a=Ia();a&&(Na(a),Gg(Hg))},Kb=(a,b)=>{a==b?setTimeout(Qa):m?postMessage({qg:a,If:"checkMailbox"}):(a=gf[a])&&a.postMessage({If:"checkMailbox"})},Ig=[],Lb=(a,b,c,d,e)=>{d/=2;Ig.length=d;e>>=3;for(var f=0;f<d;f++)Ig[f]=va[e+2*f]?va[e+2*f+1]:Fa()[e+2*f+1];a=b?hf[b]:Jg[a];Jf=c;c=a(...Ig);Jf=0;return c},
Mb=()=>{Q=0},Nb=a=>{m?postMessage({If:"cleanupThread",Ch:a}):Gf(gf[a])},Ob=()=>{},Kg=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(F()[b>>2]=hg(d));return a},Pb=(a,b,c)=>{a=gg(a);b=pg(b,"emval::as");return Kg(b,c,a)},Lg=[],Qb=(a,b,c,d)=>{a=Lg[a];b=gg(b);return a(null,b,c,d)},Mg={},Ng=a=>{var b=Mg[a];return void 0===b?T(a):b},Rb=(a,b,c,d,e)=>{a=Lg[a];b=gg(b);c=Ng(c);return a(b,b[c],d,e)},Og=()=>"object"==typeof globalThis?globalThis:Function("return this")(),Tb=a=>{if(0===a)return hg(Og());a=Ng(a);
return hg(Og()[a])},Pg=a=>{var b=Lg.length;Lg.push(a);return b},Qg=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=pg(F()[b+4*d>>2],"parameter "+d);return c},Ub=(a,b,c)=>{b=Qg(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,h=[];0===c&&h.push("obj");for(var k=["retType"],l=[d],n=0;n<a;++n)h.push("arg"+n),k.push("argType"+n),l.push(b[n]),e+=`  var arg${n} = argType${n}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[n].Ff;e+=`  var rv = ${1===c?"new func":"func.call"}(${h.join(", ")});\n`;
d.qh||(k.push("emval_returnValue"),l.push(Kg),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");k.push(e+"};\n");a=sg(k)(...l);c=`methodCaller<(${b.map(r=>r.name).join(", ")}) => ${d.name}>`;return Pg(mg(c,a))},Vb=(a,b)=>{a=gg(a);b=gg(b);return hg(a[b])},Wb=a=>{9<a&&(fg[a+1]+=1)},Xb=()=>hg([]),Yb=a=>{a=gg(a);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return hg(b)},Zb=a=>hg(Ng(a)),$b=a=>{var b=gg(a);Sf(b);Sb(a)},ac=(a,b)=>{a=pg(a,"_emval_take_value");a=a.readValueFromPointer(b);
return hg(a)};function bc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);C()[b>>2]=a.getUTCSeconds();C()[b+4>>2]=a.getUTCMinutes();C()[b+8>>2]=a.getUTCHours();C()[b+12>>2]=a.getUTCDate();C()[b+16>>2]=a.getUTCMonth();C()[b+20>>2]=a.getUTCFullYear()-1900;C()[b+24>>2]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;C()[b+28>>2]=a}
var Rg=a=>0===a%4&&(0!==a%100||0===a%400),Sg=[0,31,60,91,121,152,182,213,244,274,305,335],Tg=[0,31,59,90,120,151,181,212,243,273,304,334];
function cc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);C()[b>>2]=a.getSeconds();C()[b+4>>2]=a.getMinutes();C()[b+8>>2]=a.getHours();C()[b+12>>2]=a.getDate();C()[b+16>>2]=a.getMonth();C()[b+20>>2]=a.getFullYear()-1900;C()[b+24>>2]=a.getDay();var c=(Rg(a.getFullYear())?Sg:Tg)[a.getMonth()]+a.getDate()-1|0;C()[b+28>>2]=c;C()[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;C()[b+32>>2]=a}
function dc(a){var b=new Date(C()[a+20>>2]+1900,C()[a+16>>2],C()[a+12>>2],C()[a+8>>2],C()[a+4>>2],C()[a>>2],0),c=C()[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(f,e);0>c?C()[a+32>>2]=Number(e!=f&&h==d):0<c!=(h==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?h:e)-d)));C()[a+24>>2]=b.getDay();c=(Rg(b.getFullYear())?Sg:Tg)[b.getMonth()]+b.getDate()-1|0;C()[a+28>>2]=c;C()[a>>2]=b.getSeconds();
C()[a+4>>2]=b.getMinutes();C()[a+8>>2]=b.getHours();C()[a+12>>2]=b.getDate();C()[a+16>>2]=b.getMonth();C()[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)}function ec(a,b,c,d,e,f,h){return m?R(16,1,a,b,c,d,e,f,h):-52}function fc(a,b,c,d,e,f){if(m)return R(17,1,a,b,c,d,e,f)}var Ug={},Lc=()=>performance.timeOrigin+performance.now();
function gc(a,b){if(m)return R(18,1,a,b);Ug[a]&&(clearTimeout(Ug[a].id),delete Ug[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ug[a];Gg(()=>Vg(a,performance.timeOrigin+performance.now()))},b);Ug[a]={id:c,ei:b};return 0}
var hc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var h=Math.max(f,e);F()[a>>2]=60*h;C()[b>>2]=Number(f!=e);b=k=>{var l=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(M(a,c,17),M(b,d,17)):(M(a,d,17),M(b,c,17))},eh=(a,b)=>{Wg=a;Xg=b;if(Yg)if(Zg||(Q+=1,Zg=!0),0==a)$g=function(){setTimeout(ah,Math.max(0,bh+b-(performance.timeOrigin+performance.now()))|
0)};else if(1==a)$g=function(){ch(ah)};else if(2==a){if("undefined"==typeof dh)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);dh=d=>{c.push(d);ea?(g.setImmediates??(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else dh=setImmediate;$g=function(){dh(ah)}}},mh=(a,b,c,d,e)=>{function f(){return h<fh?(--Q,Fg(),
!1):!0}Yg=a;gh=d;var h=fh;Zg=!1;ah=function(){if(!ma)if(0<hh.length){var k=hh.shift();k.Th(k.hg);if(ih){var l=ih,n=0==l%1?l-1:Math.floor(l);ih=k.Jh?n:(8*l+(n+.5))/9}f()&&setTimeout(ah,0)}else if(f())if(jh=jh+1|0,1==Wg&&1<Xg&&0!=jh%Xg)$g();else{0==Wg&&(bh=performance.timeOrigin+performance.now());a:if(!ma){for(k of kh)if(!1===k())break a;Gg(a);for(l of lh)l()}f()&&$g()}};e||(0<b?eh(0,1E3/b):eh(1,1),$g());if(c)throw"unwind";},Zg=!1,$g=null,fh=0,Yg=null,gh=0,Wg=0,Xg=0,jh=0,hh=[],kh=[],lh=[];
function nh(){$g=null;fh++}var oh=0;function ch(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===oh)oh=b+1E3/60;else for(;b+2>=oh;)oh+=1E3/60;setTimeout(a,Math.max(oh-b,0))}}
var ph={},bh,ah,dh,ih,qh=25,rh="Emscripten OpenAL",sh={},th={},V=null,uh={0:{id:0,$f:0,uf:null,frequency:0,Nf:2,channels:1,length:0}},vh=1,wh=[],yh=a=>{if((1!==Wg||"visible"==document.visibilityState)&&4114===a.state){for(var b=xh(a),c=a.Af,d=a.zf,e=a.xf,f=0;f<a.wf.length;f++){var h=a.wf[f];c=h.gg+h.Uf;d=0;e+=h.Ig+1}k||=.1;var k=b+k;for(b=0;c<k;){if(e>=a.tf.length)if(a.Mf)e%=a.tf.length;else break;f=a.tf[e%a.tf.length];if(0===f.length){if(b++,b===a.tf.length)break}else{h=a.context.Bf.createBufferSource();
h.buffer=f.uf;h.playbackRate.value=a.playbackRate;if(f.uf.fg||f.uf.eg)h.loopStart=f.uf.fg,h.loopEnd=f.uf.eg;if(4136===a.type&&a.Mf){var l=Number.POSITIVE_INFINITY;h.loop=!0;f.uf.fg&&(h.loopStart=f.uf.fg);f.uf.eg&&(h.loopEnd=f.uf.eg)}else l=(f.uf.duration-d)/a.playbackRate;h.eh=d;h.Uf=l;h.Ig=b;b=0;h.connect(a.gain);"undefined"!=typeof h.start?(c=Math.max(c,a.context.Bf.currentTime),h.start(c,d)):"undefined"!=typeof h.noteOn&&(c=Math.max(c,a.context.Bf.currentTime),h.noteOn(c));h.gg=c;a.wf.push(h);
c+=l}d=0;e++}}},xh=a=>{var b=a.context.Bf.currentTime;if(4114!==a.state)return b;isFinite(a.Af)||(a.Af=b-a.zf/a.playbackRate,a.zf=0);for(var c;a.wf.length;){c=a.wf[0];a.xf+=c.Ig;c=c.gg+c.Uf;if(b<c)break;a.wf.shift();a.Af=c;a.zf=0;a.xf++}if(a.xf>=a.tf.length&&!a.Mf)zh(a,4116);else if(4136===a.type&&a.Mf)if(c=a.tf[0],0===c.length)a.zf=0;else{var d=(b-a.Af)*a.playbackRate,e=c.uf.fg||0,f=c.uf.eg||c.uf.duration;f<=e&&(f=c.uf.duration);d<f?a.zf=d:a.zf=e+(d-e)%(f-e)}else if(a.wf[0])a.zf=(b-a.wf[0].gg)*a.playbackRate;
else for(4136!==a.type&&a.Mf&&(c=Ah(a)/a.playbackRate,0<c&&(a.Af+=Math.floor((b-a.Af)/c)*c)),d=0;d<a.tf.length;d++){if(a.xf>=a.tf.length)if(a.Mf)a.xf%=a.tf.length;else{zh(a,4116);break}c=a.tf[a.xf];if(0<c.length){c=a.Af+c.uf.duration/a.playbackRate;if(b<c){a.zf=(b-a.Af)*a.playbackRate;break}a.Af=c}a.zf=0;a.xf++}return b},Bh=a=>{for(var b=0;b<a.wf.length;b++)a.wf[b].stop();a.wf.length=0},zh=(a,b)=>{if(4114===b){if(4114===a.state||4116==a.state)a.xf=0,a.zf=0;Bh(a);a.state=4114;a.Af=Number.NEGATIVE_INFINITY;
yh(a)}else 4115===b?4114===a.state&&(xh(a),Bh(a),a.state=4115):4116===b?4113!==a.state&&(a.state=4116,a.xf=a.tf.length,a.Af=Number.NEGATIVE_INFINITY,a.zf=0,Bh(a)):4113===b&&4113!==a.state&&(a.state=4113,a.xf=0,a.Af=Number.NEGATIVE_INFINITY,a.zf=0,Bh(a))},Eh=a=>{if(4144!==a.type){for(var b=uh[0],c=0;c<a.tf.length;c++)if(0!==a.tf[c].id){b=a.tf[c];break}1===a.Bg||2===a.Bg&&1===b.channels?a.vf||(a.vf=a.context.Bf.createPanner(),Ch(a),Dh(a),a.vf.connect(a.context.gain),a.gain.disconnect(),a.gain.connect(a.vf)):
a.vf&&(a.vf.disconnect(),a.gain.disconnect(),a.gain.connect(a.context.gain),a.vf=null)}},Fh=a=>{for(var b in a.sources)Ch(a.sources[b])},Ch=a=>{var b=a.vf;if(b)switch(b.refDistance=a.refDistance,b.maxDistance=a.maxDistance,b.rolloffFactor=a.rolloffFactor,b.panningModel=a.context.Qg?"HRTF":"equalpower",a.context.Xg?a.distanceModel:a.context.distanceModel){case 0:b.distanceModel="inverse";b.refDistance=3.40282E38;break;case 53249:case 53250:b.distanceModel="inverse";break;case 53251:case 53252:b.distanceModel=
"linear";break;case 53253:case 53254:b.distanceModel="exponential"}},Dh=a=>{if(a.vf){var b=a.vf,c=a.position[0],d=a.position[1],e=a.position[2],f=a.direction[0],h=a.direction[1],k=a.direction[2],l=a.context.listener,n=l.position[0],r=l.position[1],v=l.position[2];if(a.Ag){var t=-l.direction[0],y=-l.direction[1],E=-l.direction[2],L=l.Gg[0],z=l.Gg[1],B=l.Gg[2],N=(Ea,za,He)=>{Ea=Math.sqrt(Ea*Ea+za*za+He*He);return Ea<Number.EPSILON?0:1/Ea},u=N(t,y,E);t*=u;y*=u;E*=u;u=N(L,z,B);L*=u;z*=u;B*=u;var O=z*
E-B*y,D=B*t-L*E,P=L*y-z*t;u=N(O,D,P);O*=u;D*=u;P*=u;L=y*P-E*D;z=E*O-t*P;B=t*D-y*O;N=f;u=h;var J=k;f=N*O+u*L+J*t;h=N*D+u*z+J*y;k=N*P+u*B+J*E;N=c;u=d;J=e;c=N*O+u*L+J*t+n;d=N*D+u*z+J*y+r;e=N*P+u*B+J*E+v}b.positionX?(c!=b.positionX.value&&(b.positionX.value=c),d!=b.positionY.value&&(b.positionY.value=d),e!=b.positionZ.value&&(b.positionZ.value=e)):b.setPosition(c,d,e);b.orientationX?(f!=b.orientationX.value&&(b.orientationX.value=f),h!=b.orientationY.value&&(b.orientationY.value=h),k!=b.orientationZ.value&&
(b.orientationZ.value=k)):b.setOrientation(f,h,k);b=a.Zf;f=a.Lf[0];h=a.Lf[1];k=a.Lf[2];t=l.Lf[0];y=l.Lf[1];l=l.Lf[2];c===n&&d===r&&e===v||f===t&&h===y&&k===l?a.Zf=1:(E=a.context.speedOfSound,L=a.context.dopplerFactor,c=n-c,d=r-d,e=v-e,v=Math.sqrt(c*c+d*d+e*e),a.Zf=(E-L*Math.min((c*t+d*y+e*l)/v,E/L))/(E-L*Math.min((c*f+d*h+e*k)/v,E/L)));a.Zf!==b&&Gh(a)}},Gh=a=>{if(4114===a.state){xh(a);for(var b=1;b<a.wf.length;b++)a.wf[b].stop();1<a.wf.length&&(a.wf.length=1);if(b=a.wf[0])b.Uf=4136===a.type&&a.Mf?
Number.POSITIVE_INFINITY:(b.buffer.duration-b.eh)/a.playbackRate,b.playbackRate.value=a.playbackRate,yh(a)}},Ah=a=>{for(var b=0,c=0;c<a.tf.length;c++){var d=a.tf[c].uf;b+=d?d.duration:0}return b},Hh=(a,b)=>{var c=4114==a.state;c&&zh(a,4113);if(null!==a.tf[a.xf].uf){for(a.xf=0;b>a.tf[a.xf].uf.duration;)b-=a.tf[a.xf].uf.duration,a.xf++;a.zf=b}c&&zh(a,4114)},Ih=(a,b,c)=>{if(V)if(a=V.sources[a])if(null===c)V.sf=40962;else switch(b){case 514:1===c?(a.Ag=!0,Dh(a)):0===c?(a.Ag=!1,Dh(a)):V.sf=40963;break;
case 4097:if(!Number.isFinite(c)){V.sf=40963;break}a.coneInnerAngle=c;a.vf&&(a.vf.coneInnerAngle=c%360);break;case 4098:if(!Number.isFinite(c)){V.sf=40963;break}a.coneOuterAngle=c;a.vf&&(a.vf.coneOuterAngle=c%360);break;case 4099:if(!Number.isFinite(c)||0>=c){V.sf=40963;break}if(a.pitch===c)break;a.pitch=c;Gh(a);break;case 4100:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){V.sf=40963;break}a.position[0]=c[0];a.position[1]=c[1];a.position[2]=c[2];Dh(a);break;case 4101:if(!Number.isFinite(c[0])||
!Number.isFinite(c[1])||!Number.isFinite(c[2])){V.sf=40963;break}a.direction[0]=c[0];a.direction[1]=c[1];a.direction[2]=c[2];Dh(a);break;case 4102:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){V.sf=40963;break}a.Lf[0]=c[0];a.Lf[1]=c[1];a.Lf[2]=c[2];Dh(a);break;case 4103:if(1===c)a.Mf=!0,xh(a),4136===a.type&&0<a.wf.length&&(c=a.wf[0],c.loop=!0,c.Uf=Number.POSITIVE_INFINITY);else if(0===c){a.Mf=!1;var d=xh(a);4136===a.type&&0<a.wf.length&&(c=a.wf[0],c.loop=!1,c.Uf=a.tf[0].uf.duration/
a.playbackRate,c.gg=d-a.zf/a.playbackRate)}else V.sf=40963;break;case 4105:if(4114===a.state||4115===a.state){V.sf=40964;break}if(0===c){for(d in a.tf)a.tf[d].$f--;a.tf.length=1;a.tf[0]=uh[0];a.xf=0;a.type=4144}else{var e=uh[c];if(!e){V.sf=40963;break}for(d in a.tf)a.tf[d].$f--;a.tf.length=0;e.$f++;a.tf=[e];a.xf=0;a.type=4136}Eh(a);yh(a);break;case 4106:if(!Number.isFinite(c)||0>c){V.sf=40963;break}a.gain.gain.value=c;break;case 4109:if(!Number.isFinite(c)||0>c||c>Math.min(a.Sg,1)){V.sf=40963;break}a.Tg=
c;break;case 4110:if(!Number.isFinite(c)||c<Math.max(0,a.Tg)||1<c){V.sf=40963;break}a.Sg=c;break;case 4128:if(!Number.isFinite(c)||0>c){V.sf=40963;break}a.refDistance=c;a.vf&&(a.vf.refDistance=c);break;case 4129:if(!Number.isFinite(c)||0>c){V.sf=40963;break}a.rolloffFactor=c;a.vf&&(a.vf.rolloffFactor=c);break;case 4130:if(!Number.isFinite(c)||0>c||1<c){V.sf=40963;break}a.coneOuterGain=c;a.vf&&(a.vf.coneOuterGain=c);break;case 4131:if(!Number.isFinite(c)||0>c){V.sf=40963;break}a.maxDistance=c;a.vf&&
(a.vf.maxDistance=c);break;case 4132:if(0>c||c>Ah(a)){V.sf=40963;break}Hh(a,c);break;case 4133:d=Ah(a);if(0<d){for(var f in a.tf)if(f){e=a.tf[f].frequency;break}c/=e}if(0>c||c>d){V.sf=40963;break}Hh(a,c);break;case 4134:d=Ah(a);if(0<d){for(f in a.tf)if(f){e=a.tf[f];var h=e.frequency*e.Nf*e.channels;break}c/=h}if(0>c||c>d){V.sf=40963;break}Hh(a,c);break;case 4628:if(0!==c&&1!==c&&2!==c){V.sf=40963;break}a.Bg=c;Eh(a);break;case 8201:case 8202:case 8203:V.sf=40964;break;case 53248:switch(c){case 0:case 53249:case 53250:case 53251:case 53252:case 53253:case 53254:a.distanceModel=
c;V.Xg&&Fh(V);break;default:V.sf=40963}break;default:V.sf=40962}else V.sf=40961};
function jc(a,b,c,d,e){if(m)return R(19,1,a,b,c,d,e);if(V)if(a=uh[a])if(0>=e)V.sf=40963;else{var f=null;try{switch(b){case 4352:if(0<d){f=V.Bf.createBuffer(1,d,e);for(var h=f.getChannelData(0),k=0;k<d;++k)h[k]=.0078125*x()[c++]-1}a.Nf=1;a.channels=1;a.length=d;break;case 4353:if(0<d)for(f=V.Bf.createBuffer(1,d>>1,e),h=f.getChannelData(0),c>>=1,k=0;k<d>>1;++k)h[k]=3.0517578125E-5*A()[c++];a.Nf=2;a.channels=1;a.length=d>>1;break;case 4354:if(0<d){f=V.Bf.createBuffer(2,d>>1,e);h=f.getChannelData(0);
var l=f.getChannelData(1);for(k=0;k<d>>1;++k)h[k]=.0078125*x()[c++]-1,l[k]=.0078125*x()[c++]-1}a.Nf=1;a.channels=2;a.length=d>>1;break;case 4355:if(0<d)for(f=V.Bf.createBuffer(2,d>>2,e),h=f.getChannelData(0),l=f.getChannelData(1),c>>=1,k=0;k<d>>2;++k)h[k]=3.0517578125E-5*A()[c++],l[k]=3.0517578125E-5*A()[c++];a.Nf=2;a.channels=2;a.length=d>>2;break;case 65552:if(0<d)for(f=V.Bf.createBuffer(1,d>>2,e),h=f.getChannelData(0),c>>=2,k=0;k<d>>2;++k)h[k]=Da()[c++];a.Nf=4;a.channels=1;a.length=d>>2;break;
case 65553:if(0<d)for(f=V.Bf.createBuffer(2,d>>3,e),h=f.getChannelData(0),l=f.getChannelData(1),c>>=2,k=0;k<d>>3;++k)h[k]=Da()[c++],l[k]=Da()[c++];a.Nf=4;a.channels=2;a.length=d>>3;break;default:V.sf=40963;return}a.frequency=e;a.uf=f}catch(n){V.sf=40963}}else V.sf=40963}
function kc(a,b){if(m)return R(20,1,a,b);if(V){for(var c=0;c<a;++c){var d=C()[b+4*c>>2];if(0!==d){if(!uh[d]){V.sf=40961;return}if(uh[d].$f){V.sf=40964;return}}}for(c=0;c<a;++c)d=C()[b+4*c>>2],0!==d&&(sh[uh[d].deviceId]--,delete uh[d],wh.push(d))}}function pc(a,b,c){if(m)return R(22,1,a,b,c);switch(b){case 514:case 4097:case 4098:case 4103:case 4105:case 4128:case 4129:case 4131:case 4132:case 4133:case 4134:case 4628:case 8201:case 8202:case 53248:Ih(a,b,c);break;default:Ih(a,b,null)}}
function lc(a,b){if(m)return R(21,1,a,b);if(V){for(var c=0;c<a;++c){var d=C()[b+4*c>>2];if(!V.sources[d]){V.sf=40961;return}}for(c=0;c<a;++c)d=C()[b+4*c>>2],zh(V.sources[d],4116),pc(d,4105,0),delete V.sources[d],wh.push(d)}}function mc(a,b){if(m)return R(23,1,a,b);if(V)for(var c=0;c<a;++c){var d={deviceId:V.deviceId,id:0<wh.length?wh.pop():vh++,$f:0,uf:null,frequency:0,Nf:2,channels:1,length:0};sh[d.deviceId]++;uh[d.id]=d;C()[b+4*c>>2]=d.id}}
function nc(a,b){if(m)return R(24,1,a,b);if(V)for(var c=0;c<a;++c){var d=V.Bf.createGain();d.connect(V.gain);d={context:V,id:0<wh.length?wh.pop():vh++,type:4144,state:4113,tf:[uh[0]],wf:[],Mf:!1,pitch:1,Zf:1,gain:d,Tg:0,Sg:1,vf:null,xf:0,Af:Number.NEGATIVE_INFINITY,zf:0,Ag:!1,refDistance:1,maxDistance:3.40282E38,rolloffFactor:1,position:[0,0,0],Lf:[0,0,0],direction:[0,0,0],coneOuterGain:0,coneInnerAngle:360,coneOuterAngle:360,distanceModel:53250,Bg:2,get playbackRate(){return this.pitch*this.Zf}};
V.sources[d.id]=d;C()[b+4*c>>2]=d.id}}function oc(a){if(m)return R(25,1,a);V&&((a=V.sources[a])?zh(a,4114):V.sf=40961)}function qc(a){if(m)return R(26,1,a);if(!(a in sh)||0<sh[a])return 0;delete sh[a];wh.push(a);return 1}var Jh=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Kh=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Jh(d,c,()=>{"suspended"===a.state&&a.resume()})})})};
function rc(a,b){if(m)return R(27,1,a,b);if(!(a in sh))return 0;var c=null,d=[],e=null;if(b>>=2)for(var f=0,h=0;;){f=C()[b++];d.push(f);if(0===f)break;h=C()[b++];d.push(h);switch(f){case 4103:c||={};c.sampleRate=h;break;case 4112:case 4113:break;case 6546:switch(h){case 0:e=!1;break;case 1:e=!0;break;case 2:break;default:return 0}break;case 6550:if(0!==h)return 0;break;default:return 0}}f=window.AudioContext||window.webkitAudioContext;b=null;try{b=c?new f(c):new f}catch(n){return 0}Kh(b);"undefined"==
typeof b.createGain&&(b.createGain=b.createGainNode);c=b.createGain();c.connect(b.destination);var k={deviceId:a,id:0<wh.length?wh.pop():vh++,Hh:d,Bf:b,listener:{position:[0,0,0],Lf:[0,0,0],direction:[0,0,0],Gg:[0,0,0]},sources:[],interval:setInterval(()=>{var n=k;if(1!==Wg||"visible"==document.visibilityState)for(var r in n.sources)yh(n.sources[r])},qh),gain:c,distanceModel:53250,speedOfSound:343.3,dopplerFactor:1,Xg:!1,Qg:e||!1,sg:0,get sf(){return this.sg},set sf(n){if(0===this.sg||0===n)this.sg=
n}};sh[a]++;th[k.id]=k;if(null!==e)for(var l in th)d=th[l],d.deviceId===a&&(d.Qg=e,Fh(d));return k.id}function sc(a){if(m)return R(28,1,a);var b=th[a];V!==b&&(th[a].interval&&clearInterval(th[a].interval),sh[b.deviceId]--,delete th[a],wh.push(a))}function tc(a){if(m)return R(29,1,a);0===a?V=null:V=th[a];return 1}function uc(a){return m?R(30,1,a):a&&H(a)!==rh?0:"undefined"!=typeof AudioContext||"undefined"!=typeof webkitAudioContext?(a=0<wh.length?wh.pop():vh++,sh[a]=0,a):0}
var Cc=()=>Date.now(),Lh=1;function vc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Lh)a=performance.timeOrigin+performance.now();else return 52;va[c>>3]=BigInt(Math.round(1E6*a));return 0}
var Mh=[],yc=(a,b,c)=>{Mh.length=0;for(var d;d=x()[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Mh.push(112==d?F()[c>>2]:106==d?va[c>>3]:105==d?C()[c>>2]:Fa()[c>>3]);c+=e?8:4}return hf[a](...Mh)},Nh=(a,b)=>{Q+=1;setTimeout(()=>{--Q;Gg(a)},b)},Oh=a=>{Q+=1;ch(()=>{--Q;Gg(a)})},zc=(a,b,c)=>{var d=()=>S(a)(b);0<=c?Nh(d,c):Oh(d)},Ac=()=>{nh();Yg=null},Bc=()=>{},Dc=(a,b)=>p(H(a,b)),Ec=()=>{Q+=1;throw"unwind";};
function Fc(a){if(Ph.has(a)){var b=Ph.get(a),c=Ph;c.Df[a]=void 0;c.Yg.push(a);0<b.readyState&&4>b.readyState&&b.abort()}}function Gc(a){if(m)return R(31,1,a);Q=0;kd(a)}var zf=[];function Qh(a){var b=W.Gf[a];b.target.removeEventListener(b.Pf,b.Ng,b.cg);W.Gf.splice(a,1)}function Rh(){if(navigator.userActivation?navigator.userActivation.isActive:W.vg&&W.gh.tg){var a=W.Of;W.Of=[];for(var b of a)b.Dg(...b.Kg)}}
function Sh(a){if(!a.target)return-4;if(a.ig)a.Ng=function(c){++W.vg;W.gh=a;Rh();a.lg(c);Rh();--W.vg},a.target.addEventListener(a.Pf,a.Ng,a.cg),W.Gf.push(a),W.wh||(zf.unshift(W.uh),W.wh=!0);else for(var b=0;b<W.Gf.length;++b)W.Gf[b].target==a.target&&W.Gf[b].Pf==a.Pf&&Qh(b--);return 0}function Th(a){switch(a){case 1:return 0;case 2:return Jf;default:return a}}
var W={Ih:0,Uh:0,wg:0,pg:0,Hg:0,fi:0,Rh:0,Nh:0,$h:0,Mh:0,Sh:0,ai:0,gi:0,Eg:0,Xh(a,b,c){w().set(w().subarray(b,b+c),a)},uh(){for(;W.Gf.length;)Qh(W.Gf.length-1);W.Of=[]},vg:0,Of:[],Lh(a,b,c){function d(f,h){if(f.length!=h.length)return!1;for(var k in f)if(f[k]!=h[k])return!1;return!0}for(var e of W.Of)if(e.Dg==a&&d(e.Kg,c))return;W.Of.push({Dg:a,Wg:b,Kg:c});W.Of.sort((f,h)=>f.Wg<h.Wg)},ci(a){W.Of=W.Of.filter(b=>b.Dg!=a)},Gf:[],vh:(a,b)=>{for(var c=0;c<W.Gf.length;++c)W.Gf[c].target!=a||b&&b!=W.Gf[c].Pf||
Qh(c--)},Vh(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},X,Uh=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Vh=1,Wh=[],Xh=[],Yh=[],Zh=[],$h=[],ai=[],bi=[],ci={},If={},di=[1,1,2,2,4,4,4,2,3,4,8],ei=4,fi=0,gi=a=>{for(var b=Vh++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=Vh++;return b},hi=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=X[c](),h=f&&gi(d);f?(f.name=h,d[h]=f):Y||=1282;C()[b+4*e>>2]=h}},ii=a=>{a=32-Math.clz32(0===a?0:a-1);var b=Z.Sf[a];if(b)return b;b=X.getParameter(34965);Z.Sf[a]=X.createBuffer();X.bindBuffer(34963,Z.Sf[a]);X.bufferData(34963,
1<<a,35048);X.bindBuffer(34963,b);return Z.Sf[a]},ki=a=>{ji=!1;for(var b=0;b<Z.xg;++b){var c=Z.Vf[b];if(c.jg&&c.enabled){ji=!0;var d=c.Cg;d=0<d?a*d:c.size*di[c.type-5120]*a;var e=32-Math.clz32(0===d?0:d-1);var f=Z.Tf[e],h=Z.Qf[e];Z.Qf[e]=Z.Qf[e]+1&63;var k=f[h];k?e=k:(k=X.getParameter(34964),f[h]=X.createBuffer(),X.bindBuffer(34962,f[h]),X.bufferData(34962,1<<e,35048),X.bindBuffer(34962,k),e=f[h]);X.bindBuffer(34962,e);X.bufferSubData(34962,0,x().subarray(c.zg,c.zg+d));c.bh.call(X,b,c.size,c.type,
c.Ug,c.Cg,0)}}},li=a=>{a||=Z;if(!a.ph){a.ph=!0;var b=a.Ef;b.Zh=b.getExtension("WEBGL_multi_draw");b.Qh=b.getExtension("EXT_polygon_offset_clamp");b.Ph=b.getExtension("EXT_clip_control");b.hi=b.getExtension("WEBGL_polygon_mode");b.Oh=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Wh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Lg=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Lg)b.Lg=b.getExtension("EXT_disjoint_timer_query");
Uh(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Hf={},Y,Z,ji,mi=a=>{a=2<a?H(a):a;return If[a.slice(1)]||"canvas"==a&&Object.keys(If)[0]||"undefined"!=typeof document&&document.querySelector(a)},ni=(a,b,c)=>{var d=mi(a);if(!d)return-4;if(d.yf)a=C()[d.yf>>2],d=C()[d.yf+4>>2],C()[b>>2]=a,C()[c>>2]=d;else if(d.Jf)C()[b>>2]=d.Jf.width,C()[c>>2]=d.Jf.height;else{if(d.Wf)return-4;C()[b>>2]=d.width;C()[c>>2]=d.height}return 0};
function oi(a,b,c){return m?R(32,1,a,b,c):ni(a,b,c)}var Hc=(a,b,c)=>mi(a)?ni(a,b,c):oi(a,b,c);function Ic(){return m?R(33,1):devicePixelRatio}var pi=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],qi=a=>{a=2<a?H(a):a;return pi[a]||("undefined"!=typeof document?document.querySelector(a):null)},ri=a=>0>pi.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};
function Jc(a,b,c){if(m)return R(34,1,a,b,c);a=qi(a);if(!a)return-4;a=ri(a);Fa()[b>>3]=a.width;Fa()[c>>3]=a.height;return 0}var Kc=()=>/iPad|iPhone|iPod/.test(navigator.userAgent)?536870912:2147483648;function si(){if("undefined"!=typeof indexedDB)return indexedDB;var a=null;"object"==typeof window&&(a=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);assert(a,"IDBStore used, but indexedDB not supported");return a}var ti={};
function ui(a,b){var c=ti[a];if(c)b(null,c);else{try{var d=si().open(a,22)}catch(e){b(e);return}d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;f.objectStoreNames.contains("FILE_DATA")?e.objectStore("FILE_DATA"):f.createObjectStore("FILE_DATA")};d.onsuccess=()=>{c=d.result;ti[a]=c;b(null,c)};d.onerror=function(e){b(e.target.error||"unknown error");e.preventDefault()}}}
function vi(a,b,c){ui(a,(d,e)=>{if(d)return c(d);d=e.transaction(["FILE_DATA"],b);d.onerror=f=>{c(f.target.error||"unknown error");f.preventDefault()};d=d.objectStore("FILE_DATA");c(null,d)})}function wi(a,b,c){vi(a,"readonly",(d,e)=>{if(d)return c(d);d=e.get(b);d.onsuccess=f=>(f=f.target.result)?c(null,f):c(`file ${b} not found`);d.onerror=c})}function xi(a,b,c,d){vi(a,"readwrite",(e,f)=>{if(e)return d(e);e=f.put(c,b);e.onsuccess=()=>d();e.onerror=d})}
function yi(a,b,c){vi(a,"readonly",(d,e)=>{if(d)return c(d);d=e.count(b);d.onsuccess=f=>c(null,0<f.target.result);d.onerror=c})}
var Mc=(a,b,c,d,e)=>{Q+=1;yi(H(a),H(b),(f,h)=>{--Q;Gg(()=>{f?e&&S(e)(c):d&&S(d)(c,h)})})},Nc=(a,b,c,d,e)=>{Q+=1;wi(H(a),H(b),(f,h)=>{--Q;Gg(()=>{if(f)e&&S(e)(c);else{var k=K(h.length);x().set(h,k);S(d)(c,k,h.length);I(k)}})})},Oc=(a,b,c,d,e,f,h)=>{Q+=1;xi(H(a),H(b),new Uint8Array(x().subarray(c,c+d)),k=>{--Q;Gg(()=>{k?h&&S(h)(e):f&&S(f)(e)})})},Pc=()=>navigator.hardwareConcurrency,Qc=(a,b)=>{function c(d){S(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Rc=a=>{var b=x().length;
a>>>=0;if(a<=b)return!1;var c=/iPad|iPhone|iPod/.test(navigator.userAgent)?536870912:2147483648;if(a>c)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(c,65536*Math.ceil(Math.max(a,e)/65536))-q.buffer.byteLength+65535)/65536|0;try{q.grow(e);Ba();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},Ai=(a,b,c)=>{var d=mi(a);if(!d)return-4;d.yf&&(C()[d.yf>>2]=b,C()[d.yf+4>>2]=c);if(d.Jf||!d.Wf)d.Jf&&(d=d.Jf),a=!1,d.dg?.Ef&&(a=d.dg.Ef.getParameter(2978),
a=a instanceof Int32Array&&4===a.length?0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height:!0),d.width=b,d.height=c,a&&d.dg.Ef.viewport(0,0,b,c);else{if(d.yf){d=F()[d.yf+8>>2];a=a?H(a):"";var e=0;if(a){e=jf(a)+1;var f=K(e);f&&M(a,f,e);e=f}zi(d,e,b,c);return 1}return-4}return 0};function Bi(a,b,c){return m?R(35,1,a,b,c):Ai(a,b,c)}
var Sc=(a,b,c)=>mi(a)?Ai(a,b,c):Bi(a,b,c),Di=(a,b,c,d,e,f,h)=>{h=Th(h);W.wg||(W.wg=K(160));a={target:qi(a),Pf:f,ig:d,lg:k=>{var l=h?K(160):W.wg;Fa()[l>>3]=k.timeStamp;var n=l>>2;C()[n+2]=k.location;w()[l+12]=k.ctrlKey;w()[l+13]=k.shiftKey;w()[l+14]=k.altKey;w()[l+15]=k.metaKey;w()[l+16]=k.repeat;C()[n+5]=k.charCode;C()[n+6]=k.keyCode;C()[n+7]=k.which;M(k.key||"",l+32,32);M(k.code||"",l+64,32);M(k.char||"",l+96,32);M(k.locale||"",l+128,32);h?Ci(h,d,e,l,b):S(d)(e,l,b)&&k.preventDefault()},cg:c};return Sh(a)};
function Tc(a,b,c,d,e){return m?R(36,1,a,b,c,d,e):Di(a,b,c,d,2,"keydown",e)}function Uc(a,b,c,d,e){return m?R(37,1,a,b,c,d,e):Di(a,b,c,d,3,"keyup",e)}
var Vc=(a,b,c)=>{a=S(a);mh(a,b,c)},Ei=(a,b,c)=>{Fa()[a>>3]=b.timeStamp;var d=a>>2;C()[d+2]=b.screenX;C()[d+3]=b.screenY;C()[d+4]=b.clientX;C()[d+5]=b.clientY;w()[a+24]=b.ctrlKey;w()[a+25]=b.shiftKey;w()[a+26]=b.altKey;w()[a+27]=b.metaKey;A()[2*d+14]=b.button;A()[2*d+15]=b.buttons;C()[d+8]=b.movementX;C()[d+9]=b.movementY;a=ri(c);C()[d+10]=b.clientX-(a.left|0);C()[d+11]=b.clientY-(a.top|0)},Fi=(a,b,c,d,e,f,h)=>{h=Th(h);W.pg||(W.pg=K(64));a=qi(a);return Sh({target:a,tg:"mousemove"!=f&&"mouseenter"!=
f&&"mouseleave"!=f,Pf:f,ig:d,lg:(k=event)=>{Ei(W.pg,k,a);if(h){var l=K(64);Ei(l,k,a);Ci(h,d,e,l,b)}else S(d)(e,W.pg,b)&&k.preventDefault()},cg:c})};function Wc(a,b,c,d,e){return m?R(38,1,a,b,c,d,e):Fi(a,b,c,d,5,"mousedown",e)}function Xc(a,b,c,d,e){return m?R(39,1,a,b,c,d,e):Fi(a,b,c,d,8,"mousemove",e)}function Yc(a,b,c,d,e){return m?R(40,1,a,b,c,d,e):Fi(a,b,c,d,6,"mouseup",e)}
var Gi=(a,b,c,d,e,f,h)=>{h=Th(h);W.Eg||(W.Eg=K(1552));a=qi(a);return Sh({target:a,tg:"touchstart"==f||"touchend"==f,Pf:f,ig:d,lg:k=>{var l={},n=k.touches;for(var r of n)r.Rg=r.Vg=0,l[r.identifier]=r;for(var v of k.changedTouches)v.Rg=1,l[v.identifier]=v;for(var t of k.targetTouches)l[t.identifier].Vg=1;n=h?K(1552):W.Eg;Fa()[n>>3]=k.timeStamp;w()[n+12]=k.ctrlKey;w()[n+13]=k.shiftKey;w()[n+14]=k.altKey;w()[n+15]=k.metaKey;r=n+16;v=ri(a);t=0;for(let y of Object.values(l))if(l=r>>2,C()[l]=y.identifier,
C()[l+1]=y.screenX,C()[l+2]=y.screenY,C()[l+3]=y.clientX,C()[l+4]=y.clientY,C()[l+5]=y.pageX,C()[l+6]=y.pageY,w()[r+28]=y.Rg,w()[r+29]=y.Vg,C()[l+8]=y.clientX-(v.left|0),C()[l+9]=y.clientY-(v.top|0),r+=48,31<++t)break;C()[n+8>>2]=t;h?Ci(h,d,e,n,b):S(d)(e,n,b)&&k.preventDefault()},cg:c})};function Zc(a,b,c,d,e){return m?R(41,1,a,b,c,d,e):Gi(a,b,c,d,23,"touchend",e)}function $c(a,b,c,d,e){return m?R(42,1,a,b,c,d,e):Gi(a,b,c,d,24,"touchmove",e)}
function ad(a,b,c,d,e){return m?R(43,1,a,b,c,d,e):Gi(a,b,c,d,22,"touchstart",e)}var Hi=(a,b,c,d,e)=>{e=Th(e);W.Hg||(W.Hg=K(96));return Sh({target:a,tg:!0,Pf:"wheel",ig:d,lg:(f=event)=>{var h=e?K(96):W.Hg;Ei(h,f,a);Fa()[h+64>>3]=f.deltaX;Fa()[h+72>>3]=f.deltaY;Fa()[h+80>>3]=f.deltaZ;C()[h+88>>2]=f.deltaMode;e?Ci(e,d,9,h,b):S(d)(9,h,b)&&f.preventDefault()},cg:c})};function bd(a,b,c,d,e){return m?R(44,1,a,b,c,d,e):(a=qi(a))?"undefined"!=typeof a.onwheel?Hi(a,b,c,d,e):-1:-4}
function Ii(a){var b=Ph,c=b.Yg.pop()||b.Df.length;b.Df[c]=a;return c}class Ji{Df=[void 0];Yg=[];get(a){return this.Df[a]}has(a){return void 0!==this.Df[a]}}function Ki(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b}var Ph,Li;
function Mi(a,b,c,d,e){function f(){var D=0,P=0;u.response&&B&&0===F()[a+12>>2]&&(P=u.response.byteLength);0<P&&(D=K(P),x().set(new Uint8Array(u.response),D));F()[a+12>>2]=D;Ni(a+16,P);Ni(a+24,0);(D=u.response?u.response.byteLength:0)&&Ni(a+32,D);A()[a+40>>1]=u.readyState;A()[a+42>>1]=u.status;u.statusText&&M(u.statusText,a+44,64)}var h=F()[a+8>>2];if(h){var k=H(h),l=a+108,n=H(l+0);n||="GET";var r=F()[l+56>>2],v=F()[l+68>>2],t=F()[l+72>>2];h=F()[l+76>>2];var y=F()[l+80>>2],E=F()[l+84>>2],L=F()[l+
88>>2],z=F()[l+52>>2],B=!!(z&1),N=!!(z&2);z=!!(z&64);v=v?H(v):void 0;t=t?H(t):void 0;var u=new XMLHttpRequest;u.withCredentials=!!x()[l+60];u.open(n,k,!z,v,t);z||(u.timeout=r);u.Df=k;u.responseType="arraybuffer";y&&(k=H(y),u.overrideMimeType(k));if(h)for(;;){l=F()[h>>2];if(!l)break;k=F()[h+4>>2];if(!k)break;h+=8;l=H(l);k=H(k);u.setRequestHeader(l,k)}var O=Ii(u);F()[a>>2]=O;h=E&&L?x().slice(E,E+L):null;u.onload=D=>{Ph.has(O)&&(f(),200<=u.status&&300>u.status?b?.(a,u,D):c?.(a,u,D))};u.onerror=D=>{Ph.has(O)&&
(f(),c?.(a,u,D))};u.ontimeout=D=>{Ph.has(O)&&c?.(a,u,D)};u.onprogress=D=>{if(Ph.has(O)){var P=B&&N&&u.response?u.response.byteLength:0,J=0;0<P&&B&&N&&(J=K(P),x().set(new Uint8Array(u.response),J));F()[a+12>>2]=J;Ni(a+16,P);Ni(a+24,D.loaded-P);Ni(a+32,D.total);A()[a+40>>1]=u.readyState;3<=u.readyState&&0===u.status&&0<D.loaded&&(u.status=200);A()[a+42>>1]=u.status;u.statusText&&M(u.statusText,a+44,64);d?.(a,u,D);J&&I(J)}};u.onreadystatechange=D=>{Ph.has(O)?(A()[a+40>>1]=u.readyState,2<=u.readyState&&
(A()[a+42>>1]=u.status),e?.(a,u,D)):--Q};try{u.send(h)}catch(D){c?.(a,u,D)}}else c(a,0,"no url specified!")}var Ni=(a,b)=>{F()[a>>2]=b;var c=F()[a>>2];F()[a+4>>2]=(b-c)/4294967296};
function Oi(a,b,c,d){var e=Li;if(e){var f=a+108;(f=F()[f+64>>2])||(f=F()[a+8>>2]);var h=H(f);try{var k=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);k.onsuccess=()=>{A()[a+40>>1]=4;A()[a+42>>1]=200;M("OK",a+44,64);c(a,0,h)};k.onerror=l=>{A()[a+40>>1]=4;A()[a+42>>1]=413;M("Payload Too Large",a+44,64);d(a,0,l)}}catch(l){d(a,0,l)}}else d(a,0,"IndexedDB not available!")}
function Pi(a,b,c){var d=Li;if(d){var e=a+108;(e=F()[e+64>>2])||(e=F()[a+8>>2]);e=H(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=h=>{if(h.target.result){h=h.target.result;var k=h.byteLength||h.length,l=K(k);x().set(new Uint8Array(h),l);F()[a+12>>2]=l;Ni(a+16,k);Ni(a+24,0);Ni(a+32,k);A()[a+40>>1]=4;A()[a+42>>1]=200;M("OK",a+44,64);b(a,0,h)}else A()[a+40>>1]=4,A()[a+42>>1]=404,M("Not Found",a+44,64),c(a,0,"no data")};f.onerror=h=>{A()[a+40>>1]=4;A()[a+42>>
1]=404;M("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Qi(a,b,c){var d=Li;if(d){var e=a+108;(e=F()[e+64>>2])||(e=F()[a+8>>2]);e=H(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=h=>{h=h.target.result;F()[a+12>>2]=0;Ni(a+16,0);Ni(a+24,0);Ni(a+32,0);A()[a+40>>1]=4;A()[a+42>>1]=200;M("OK",a+44,64);b(a,0,h)};f.onerror=h=>{A()[a+40>>1]=4;A()[a+42>>1]=404;M("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function cd(a,b,c,d,e){function f(J){t?J():Gg(J)}Q+=1;var h=a+108,k=F()[h+36>>2],l=F()[h+40>>2],n=F()[h+44>>2],r=F()[h+48>>2],v=F()[h+52>>2],t=!!(v&64),y=J=>{--Q;f(()=>{k?S(k)(J):b?.(J)})},E=J=>{f(()=>{n?S(n)(J):d?.(J)})},L=J=>{--Q;f(()=>{l?S(l)(J):c?.(J)})},z=J=>{f(()=>{r?S(r)(J):e?.(J)})},B=J=>{Mi(J,y,L,E,z)},N=(J,Ea)=>{Oi(J,Ea.response,za=>{--Q;f(()=>{k?S(k)(za):b?.(za)})},za=>{--Q;f(()=>{k?S(k)(za):b?.(za)})})},u=J=>{Mi(J,N,L,E,z)},O=H(h+0),D=!!(v&16),P=!!(v&4);v=!!(v&32);if("EM_IDB_STORE"===
O)B=F()[h+84>>2],h=F()[h+88>>2],Oi(a,x().slice(B,B+h),y,L);else if("EM_IDB_DELETE"===O)Qi(a,y,L);else if(D){if(v)return 0;Mi(a,P?N:y,L,E,z)}else Pi(a,y,v?L:P?u:B);return a}
var Ri=["default","low-power","high-performance"],dd=(a,b)=>{var c=b>>2,d=C()[c+2];c={alpha:!!w()[b+0],depth:!!w()[b+1],stencil:!!w()[b+2],antialias:!!w()[b+3],premultipliedAlpha:!!w()[b+4],preserveDrawingBuffer:!!w()[b+5],powerPreference:Ri[d],failIfMajorPerformanceCaveat:!!w()[b+12],rh:C()[c+4],Yh:C()[c+5],Mg:w()[b+24],Og:w()[b+25],bi:C()[c+7],di:w()[b+32]};a=mi(a);a?.canvas&&(a=a.canvas);if(!a)return 0;a.Jf&&(a=a.Jf);if(c.Og){if(!(a.transferControlToOffscreen||"undefined"!=typeof OffscreenCanvas&&
a instanceof OffscreenCanvas))return 0;if(a.transferControlToOffscreen){if(!a.Wf)If[a.id]={canvas:a.transferControlToOffscreen(),yf:K(12),id:a.id},a.Wf=!0;else if(!If[a.id])return 0;a=If[a.id].canvas}}if(d=a.getContext("webgl2",c)){a=K(8);F()[a+4>>2]=Ia();b={handle:a,attributes:c,version:c.rh,Ef:d};d.canvas&&(d.canvas.dg=b);ci[a]=b;("undefined"==typeof c.Mg||c.Mg)&&li(b);b.xg=b.Ef.getParameter(34921);b.Vf=[];for(c=0;c<b.xg;c++)b.Vf[c]={enabled:!1,jg:!1,size:0,type:0,Ug:0,Cg:0,zg:0,bh:null};b.Qf=[];
b.rg=[];b.Qf.length=b.rg.length=22;b.Tf=[];b.ag=[];b.Tf.length=b.ag.length=22;b.Sf=[];b.Sf.length=22;for(c=0;21>=c;++c){b.Sf[c]=null;b.Qf[c]=b.rg[c]=0;b.Tf[c]=[];b.ag[c]=[];d=b.Tf[c];var e=b.ag[c];d.length=e.length=64;for(var f=0;64>f;++f)d[f]=e[f]=null}}else a=0;return a};function ed(a){Z==a&&(Z=0);Z===ci[a]&&(Z=null);"object"==typeof W&&W.vh(ci[a].Ef.canvas);ci[a]?.Ef.canvas&&(ci[a].Ef.canvas.dg=void 0);I(ci[a].handle);ci[a]=null}
var fd=a=>{Z=ci[a];g.ctx=X=Z?.Ef;return!a||X?0:-5},Si={},Ui=()=>{if(!Ti){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in Si)void 0===Si[b]?delete a[b]:a[b]=Si[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ti=c}return Ti},Ti;
function hd(a,b){if(m)return R(45,1,a,b);var c=0;Ui().forEach((d,e)=>{var f=b+c;e=F()[a+4*e>>2]=f;for(f=0;f<d.length;++f)w()[e++]=d.charCodeAt(f);w()[e]=0;c+=d.length+1});return 0}function jd(a,b){if(m)return R(46,1,a,b);var c=Ui();F()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);F()[b>>2]=d;return 0}function ld(a){return m?R(47,1,a):52}
function md(a,b){if(m)return R(48,1,a,b);var c=0;if(0==a)c=2;else if(1==a||2==a)c=64;w()[b]=2;A()[b+2>>1]=1;va[b+8>>3]=BigInt(c);va[b+16>>3]=BigInt(0);return 0}function nd(a,b,c,d){return m?R(49,1,a,b,c,d):52}function od(a,b,c,d){return m?R(50,1,a,b,c,d):70}var Bf=[null,[],[]],Cf=(a,b)=>{var c=Bf[a];0===b||10===b?((1===a?ka:p)(Pf(c)),c.length=0):c.push(b)};
function pd(a,b,c,d){if(m)return R(51,1,a,b,c,d);for(var e=0,f=0;f<c;f++){var h=F()[b>>2],k=F()[b+4>>2];b+=8;for(var l=0;l<k;l++)Cf(a,x()[h+l]);e+=k}F()[d>>2]=e;return 0}
var sd=a=>X.activeTexture(a),td=(a,b)=>{X.attachShader(Xh[a],ai[b])},ud=(a,b)=>{if(b&&!Wh[b]){var c=X.createBuffer();c.name=b;Wh[b]=c}34962==a?X.Xf=b:34963==a&&(X.Yf=b);35051==a?X.ug=b:35052==a&&(X.kg=b);X.bindBuffer(a,Wh[b])},vd=(a,b)=>{X.bindFramebuffer(a,Yh[b])},wd=(a,b)=>{X.bindRenderbuffer(a,Zh[b])},xd=(a,b)=>{X.bindTexture(a,$h[b])},yd=a=>{X.bindVertexArray(bi[a]);a=X.getParameter(34965);X.Yf=a?a.name|0:0},zd=(a,b)=>X.blendFunc(a,b),Ad=(a,b,c,d)=>X.blendFuncSeparate(a,b,c,d),Bd=(a,b,c,d,e,f,
h,k,l,n)=>X.blitFramebuffer(a,b,c,d,e,f,h,k,l,n),Cd=(a,b,c,d)=>{c&&b?X.bufferData(a,x(),d,c,b):X.bufferData(a,b,d)},Dd=(a,b,c,d)=>{c&&X.bufferSubData(a,b,x(),d,c)},Ed=a=>X.checkFramebufferStatus(a),Fd=a=>X.clear(a),Gd=(a,b,c,d)=>X.clearColor(a,b,c,d),Hd=a=>X.clearDepth(a),Id=(a,b,c,d)=>{X.colorMask(!!a,!!b,!!c,!!d)},Jd=a=>{X.compileShader(ai[a])},Kd=()=>{var a=gi(Xh),b=X.createProgram();b.name=a;b.og=b.mg=b.ng=0;b.Fg=1;Xh[a]=b;return a},Ld=a=>{var b=gi(ai);ai[b]=X.createShader(a);return b},Md=a=>
X.cullFace(a),Nd=(a,b)=>{for(var c=0;c<a;c++){var d=C()[b+4*c>>2],e=Wh[d];e&&(X.deleteBuffer(e),e.name=0,Wh[d]=null,d==X.Xf&&(X.Xf=0),d==X.Yf&&(X.Yf=0),d==X.ug&&(X.ug=0),d==X.kg&&(X.kg=0))}},Od=(a,b)=>{for(var c=0;c<a;++c){var d=C()[b+4*c>>2],e=Yh[d];e&&(X.deleteFramebuffer(e),e.name=0,Yh[d]=null)}},Pd=a=>{if(a){var b=Xh[a];b?(X.deleteProgram(b),b.name=0,Xh[a]=null):Y||=1281}},Qd=(a,b)=>{for(var c=0;c<a;c++){var d=C()[b+4*c>>2],e=Zh[d];e&&(X.deleteRenderbuffer(e),e.name=0,Zh[d]=null)}},Rd=a=>{if(a){var b=
ai[a];b?(X.deleteShader(b),ai[a]=null):Y||=1281}},Sd=(a,b)=>{for(var c=0;c<a;c++){var d=C()[b+4*c>>2],e=$h[d];e&&(X.deleteTexture(e),e.name=0,$h[d]=null)}},Td=(a,b)=>{for(var c=0;c<a;c++){var d=C()[b+4*c>>2];X.deleteVertexArray(bi[d]);bi[d]=null}},Ud=a=>X.depthFunc(a),Vd=a=>{X.depthMask(!!a)},Wd=(a,b)=>{X.detachShader(Xh[a],ai[b])},Xd=a=>X.disable(a),Yd=(a,b,c)=>{ki(b+c);X.drawArrays(a,b,c);ji&&X.bindBuffer(34962,Wh[X.Xf])},Vi=[],Zd=(a,b)=>{for(var c=Vi[a],d=0;d<a;d++)c[d]=C()[b+4*d>>2];X.drawBuffers(c)},
$d=(a,b,c,d)=>{var e=0;if(!X.Yf){var f=1*di[c-5120]*b;var h=ii(f);X.bindBuffer(34963,h);X.bufferSubData(34963,0,x().subarray(d,d+f));if(0<b)for(h=0;h<Z.xg;++h)if(f=Z.Vf[h],f.jg&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:Y||=1282;return}e=(new e(x().buffer,d,b)).reduce((k,l)=>Math.max(k,l))+1;break}d=0}ki(e);X.drawElements(a,b,c,d);ji&&X.bindBuffer(34962,Wh[X.Xf]);X.Yf||X.bindBuffer(34963,null)},ae=a=>X.enable(a),be=a=>{Z.Vf[a].enabled=
!0;X.enableVertexAttribArray(a)},ce=(a,b,c,d)=>{X.framebufferRenderbuffer(a,b,c,Zh[d])},de=(a,b,c,d,e)=>{X.framebufferTexture2D(a,b,c,$h[d],e)},ee=a=>X.frontFace(a),fe=(a,b)=>{hi(a,b,"createBuffer",Wh)},ge=(a,b)=>{hi(a,b,"createFramebuffer",Yh)},he=(a,b)=>{hi(a,b,"createRenderbuffer",Zh)},ie=(a,b)=>{hi(a,b,"createTexture",$h)},je=(a,b)=>{hi(a,b,"createVertexArray",bi)},ke=a=>X.generateMipmap(a),le=(a,b,c,d)=>{a=X.getAttachedShaders(Xh[a]);var e=a.length;e>b&&(e=b);C()[c>>2]=e;for(b=0;b<e;++b)c=ai.indexOf(a[b]),
C()[d+4*b>>2]=c},me=(a,b)=>X.getAttribLocation(Xh[a],H(b)),Wi=()=>{var a=Uh(X);return a=a.concat(a.map(b=>"GL_"+b))},Xi=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(Y||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=X.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>Z.version){Y||=1282;return}d=Wi().length;break;case 33307:case 33308:if(2>Z.version){Y||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=X.getParameter(a),typeof e){case "number":d=
e;break;case "boolean":d=e?1:0;break;case "string":Y||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:Y||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:C()[b+4*a>>
2]=e[a];break;case 2:Da()[b+4*a>>2]=e[a];break;case 4:w()[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Y||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Y||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:Ni(b,d);break;case 0:C()[b>>2]=d;break;case 2:Da()[b>>2]=d;break;case 4:w()[b]=d?1:0}}else Y||=1281},ne=(a,b)=>Xi(a,
b,4),oe=()=>{var a=X.getError()||Y;Y=0;return a},pe=(a,b)=>Xi(a,b,0),qe=(a,b,c,d)=>{a=X.getProgramInfoLog(Xh[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(C()[c>>2]=b)},re=(a,b,c)=>{if(c)if(a>=Vh)Y||=1281;else if(a=Xh[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),C()[c>>2]=a.length+1;else if(35719==b){if(!a.og){var d=X.getProgramParameter(a,35718);for(b=0;b<d;++b)a.og=Math.max(a.og,X.getActiveUniform(a,b).name.length+1)}C()[c>>2]=a.og}else if(35722==b){if(!a.mg)for(d=
X.getProgramParameter(a,35721),b=0;b<d;++b)a.mg=Math.max(a.mg,X.getActiveAttrib(a,b).name.length+1);C()[c>>2]=a.mg}else if(35381==b){if(!a.ng)for(d=X.getProgramParameter(a,35382),b=0;b<d;++b)a.ng=Math.max(a.ng,X.getActiveUniformBlockName(a,b).length+1);C()[c>>2]=a.ng}else C()[c>>2]=X.getProgramParameter(a,b);else Y||=1281},se=(a,b,c,d)=>{a=X.getShaderInfoLog(ai[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(C()[c>>2]=b)},te=(a,b,c)=>{c?35716==b?(a=X.getShaderInfoLog(ai[a]),null===a&&
(a="(unknown error)"),a=a?a.length+1:0,C()[c>>2]=a):35720==b?(a=(a=X.getShaderSource(ai[a]))?a.length+1:0,C()[c>>2]=a):C()[c>>2]=X.getShaderParameter(ai[a],b):Y||=1281},Yi=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ue=(a,b)=>{b=H(b);if(a=Xh[a]){var c=a,d=c.bg,e=c.ah,f;if(!d){c.bg=d={};c.$g={};var h=X.getProgramParameter(c,35718);for(f=0;f<h;++f){var k=X.getActiveUniform(c,f);var l=k.name;k=k.size;var n=Yi(l);n=0<n?l.slice(0,n):l;var r=c.Fg;c.Fg+=k;e[n]=[k,r];for(l=0;l<k;++l)d[r]=l,c.$g[r++]=n}}c=a.bg;
d=0;e=b;f=Yi(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.ah[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else Y||=1281;return-1},ve=a=>(a=Wh[a])?X.isBuffer(a):0,we=a=>X.isEnabled(a),xe=a=>(a=Yh[a])?X.isFramebuffer(a):0,ye=a=>(a=Xh[a])?X.isProgram(a):0,ze=a=>(a=Zh[a])?X.isRenderbuffer(a):0,Ae=a=>(a=ai[a])?X.isShader(a):0,Be=a=>(a=$h[a])?X.isTexture(a):0,Ce=a=>{a=Xh[a];X.linkProgram(a);a.bg=0;a.ah={}},De=(a,b)=>{3317==a?ei=b:3314==a&&(fi=b);X.pixelStorei(a,
b)},Ee=(a,b)=>X.polygonOffset(a,b),Fe=a=>X.readBuffer(a),Zi=a=>{a-=5120;return 0==a?w():1==a?x():2==a?A():4==a?C():6==a?Da():5==a||28922==a||28520==a||30779==a||30782==a?F():Ca()},$i=(a,b,c,d,e)=>{a=Zi(a);b=d*((fi||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ei-1&-ei);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Ge=(a,b,c,d,e,f,h)=>{if(X.ug)X.readPixels(a,b,c,d,e,f,h);else{var k=Zi(f);h>>>=
31-Math.clz32(k.BYTES_PER_ELEMENT);X.readPixels(a,b,c,d,e,f,k,h)}},Ie=(a,b,c,d)=>X.renderbufferStorage(a,b,c,d),Je=(a,b,c,d,e)=>X.renderbufferStorageMultisample(a,b,c,d,e),Ke=(a,b,c,d)=>X.scissor(a,b,c,d),Le=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var h=d?F()[d+4*f>>2]:void 0;e+=H(F()[c+4*f>>2],h)}X.shaderSource(ai[a],e)},Me=(a,b,c,d,e,f,h,k,l)=>{if(X.kg)X.texImage2D(a,b,c,d,e,f,h,k,l);else if(l){var n=Zi(k);l>>>=31-Math.clz32(n.BYTES_PER_ELEMENT);X.texImage2D(a,b,c,d,e,f,h,k,n,l)}else n=l?$i(k,h,d,
e,l):null,X.texImage2D(a,b,c,d,e,f,h,k,n)},Ne=(a,b,c)=>X.texParameteri(a,b,c),Oe=(a,b,c,d,e,f,h,k,l)=>{if(X.kg)X.texSubImage2D(a,b,c,d,e,f,h,k,l);else if(l){var n=Zi(k);X.texSubImage2D(a,b,c,d,e,f,h,k,n,l>>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else l=l?$i(k,h,e,f,l):null,X.texSubImage2D(a,b,c,d,e,f,h,k,l)},aj=a=>{var b=X.hh;if(b){var c=b.bg[a];"number"==typeof c&&(b.bg[a]=c=X.getUniformLocation(b,b.$g[a]+(0<c?`[${c}]`:"")));return c}Y||=1282},Pe=(a,b)=>{X.uniform1f(aj(a),b)},Qe=(a,b)=>{X.uniform1i(aj(a),
b)},Re=(a,b,c)=>{b&&X.uniform2fv(aj(a),Da(),c>>2,2*b)},Se=(a,b,c)=>{b&&X.uniform3fv(aj(a),Da(),c>>2,3*b)},Te=(a,b,c,d,e)=>{X.uniform4f(aj(a),b,c,d,e)},Ue=(a,b,c)=>{b&&X.uniform4fv(aj(a),Da(),c>>2,4*b)},Ve=(a,b,c,d)=>{b&&X.uniformMatrix4fv(aj(a),!!c,Da(),d>>2,16*b)},We=a=>{a=Xh[a];X.useProgram(a);X.hh=a},Xe=(a,b,c,d,e,f)=>{var h=Z.Vf[a];X.Xf?(h.jg=!1,X.vertexAttribPointer(a,b,c,!!d,e,f)):(h.size=b,h.type=c,h.Ug=d,h.Cg=e,h.zg=f,h.jg=!0,h.bh=function(k,l,n,r,v,t){this.vertexAttribPointer(k,l,n,r,v,t)})},
Ye=(a,b,c,d)=>X.viewport(a,b,c,d),bj=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),cj=a=>{(cj=bj())(a)},af=(a,b)=>{cj(x().subarray(a,a+b));return 0},dj=(a,b,c,d)=>{var e={string:n=>{var r=0;if(null!==n&&void 0!==n&&0!==n){r=jf(n)+1;var v=sf(r);M(n,v,r);r=v}return r},array:n=>{var r=sf(n.length);w().set(n,r);return r}};a=g["_"+a];var f=[],h=0;if(d)for(var k=0;k<d.length;k++){var l=e[c[k]];l?(0===h&&(h=rf()),f[k]=l(d[k])):f[k]=d[k]}c=a(...f);return c=function(n){0!==h&&uf(h);return"string"===
b?H(n):"boolean"===b?!!n:n}(c)};m||mf.unshift(()=>{Ta++;Va()});Xf=g.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var ej=Array(256),fj=0;256>fj;++fj)ej[fj]=String.fromCharCode(fj);ag=ej;U=g.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};fg.push(0,1,void 0,1,null,1,!0,1,!1,1);g.count_emval_handles=()=>fg.length/2-5-eg.length;
vg=g.UnboundTypeError=((a,b)=>{var c=mg(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");g.requestAnimationFrame=ch;g.pauseMainLoop=nh;
g.resumeMainLoop=function(){fh++;var a=Wg,b=Xg,c=Yg;Yg=null;mh(c,0,!1,gh,!0);eh(a,b);$g()};var gj=()=>{if(Z){var a=Z.Tf;Z.Tf=Z.ag;Z.ag=a;a=Z.Qf;Z.Qf=Z.rg;Z.rg=a;for(a=0;21>=a;++a)Z.Qf[a]=0}};"undefined"!=typeof ph&&kh.push(gj);Ph=new Ji;m||(Ta++,Ki(a=>{Li=a;Va()},()=>{Li=!1;Va()}));var hj=()=>{Z&&!Hf.Kh&&!Z.attributes.Og&&Z.Ef.commit&&Z.Ef.commit()};"undefined"!=typeof ph&&kh.push(hj);for(var ij=0;32>ij;++ij)Vi.push(Array(ij));
var Jg=[$e,xf,Qf,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,qb,rb,sb,ec,fc,gc,jc,kc,lc,pc,mc,nc,oc,qc,rc,sc,tc,uc,Gc,oi,Ic,Jc,Bi,Tc,Uc,Wc,Xc,Yc,Zc,$c,ad,bd,hd,jd,ld,md,nd,od,pd],cb,G;
(async function(){function a(d,e){G=d.exports;Ef.push(G.cf);Mf=G.df;la=e;Va();return G}Ta++;var b=bb();if(m)return new Promise(d=>{Ga=e=>{var f=new WebAssembly.Instance(e,bb());d(a(f,e))}});Ya??=g.locateFile?ha+"shenai_sdk.wasm":(new URL("shenai_sdk.wasm",import.meta.url)).href;try{var c=await ab(b);return a(c.instance,c.module)}catch(d){return ba(d),Promise.reject(d)}})();var ng=a=>(ng=G.ad)(a),Oa=()=>(Oa=G.bd)(),Ci=(a,b,c,d,e)=>(Ci=G.cd)(a,b,c,d,e),zi=(a,b,c,d)=>(zi=G.dd)(a,b,c,d);
g.__ZN4shen10InitializeENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_NS_23initialization_settingsE=(a,b,c)=>(g.__ZN4shen10InitializeENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_NS_23initialization_settingsE=G.ed)(a,b,c);g.__ZN4shen13IsInitializedEv=()=>(g.__ZN4shen13IsInitializedEv=G.fd)();g.__ZN4shen12DeinitializeEv=()=>(g.__ZN4shen12DeinitializeEv=G.gd)();g.__ZN4shen15FinalizeTracingEv=()=>(g.__ZN4shen15FinalizeTracingEv=G.hd)();
g.__ZN4shen18GetSDKConfigStringEv=a=>(g.__ZN4shen18GetSDKConfigStringEv=G.id)(a);g.__ZN4shen14ApplySDKConfigENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE=a=>(g.__ZN4shen14ApplySDKConfigENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE=G.jd)(a);g.__ZN4shen16SetOperatingModeENS_13OperatingModeE=a=>(g.__ZN4shen16SetOperatingModeENS_13OperatingModeE=G.kd)(a);g.__ZN4shen16GetOperatingModeEv=()=>(g.__ZN4shen16GetOperatingModeEv=G.ld)();
g.__ZN4shen9SetScreenENS_6ScreenE=a=>(g.__ZN4shen9SetScreenENS_6ScreenE=G.md)(a);g.__ZN4shen9GetScreenEv=()=>(g.__ZN4shen9GetScreenEv=G.nd)();g.__ZN4shen16SetPrecisionModeENS_13PrecisionModeE=a=>(g.__ZN4shen16SetPrecisionModeENS_13PrecisionModeE=G.od)(a);g.__ZN4shen16GetPrecisionModeEv=()=>(g.__ZN4shen16GetPrecisionModeEv=G.pd)();g.__ZN4shen20SetMeasurementPresetENS_17MeasurementPresetE=a=>(g.__ZN4shen20SetMeasurementPresetENS_17MeasurementPresetE=G.qd)(a);
g.__ZN4shen20GetMeasurementPresetEv=()=>(g.__ZN4shen20GetMeasurementPresetEv=G.rd)();g.__ZN4shen22SetBpCalibrationOffsetEdd=(a,b)=>(g.__ZN4shen22SetBpCalibrationOffsetEdd=G.sd)(a,b);g.__ZN4shen26GetCustomMeasurementConfigEv=a=>(g.__ZN4shen26GetCustomMeasurementConfigEv=G.td)(a);g.__ZN4shen26SetCustomMeasurementConfigENS_25custom_measurement_configE=a=>(g.__ZN4shen26SetCustomMeasurementConfigENS_25custom_measurement_configE=G.ud)(a);
g.__ZN4shen19SetCustomColorThemeENS_18custom_color_themeE=a=>(g.__ZN4shen19SetCustomColorThemeENS_18custom_color_themeE=G.vd)(a);g.__ZN4shen19GetCustomColorThemeEv=a=>(g.__ZN4shen19GetCustomColorThemeEv=G.wd)(a);g.__ZN4shen13SetCameraModeENS_10CameraModeE=a=>(g.__ZN4shen13SetCameraModeENS_10CameraModeE=G.xd)(a);g.__ZN4shen13GetCameraModeEv=()=>(g.__ZN4shen13GetCameraModeEv=G.yd)();
g.__ZN4shen22SelectCameraByDeviceIdENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8optionalIbEE=(a,b)=>(g.__ZN4shen22SelectCameraByDeviceIdENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8optionalIbEE=G.zd)(a,b);g.__ZN4shen20SetShowUserInterfaceEb=a=>(g.__ZN4shen20SetShowUserInterfaceEb=G.Ad)(a);g.__ZN4shen20GetShowUserInterfaceEv=()=>(g.__ZN4shen20GetShowUserInterfaceEv=G.Bd)();
g.__ZN4shen29SetShowFacePositioningOverlayEb=a=>(g.__ZN4shen29SetShowFacePositioningOverlayEb=G.Cd)(a);g.__ZN4shen29GetShowFacePositioningOverlayEv=()=>(g.__ZN4shen29GetShowFacePositioningOverlayEv=G.Dd)();g.__ZN4shen21SetShowVisualWarningsEb=a=>(g.__ZN4shen21SetShowVisualWarningsEb=G.Ed)(a);g.__ZN4shen21GetShowVisualWarningsEv=()=>(g.__ZN4shen21GetShowVisualWarningsEv=G.Fd)();g.__ZN4shen19SetEnableCameraSwapEb=a=>(g.__ZN4shen19SetEnableCameraSwapEb=G.Gd)(a);
g.__ZN4shen19GetEnableCameraSwapEv=()=>(g.__ZN4shen19GetEnableCameraSwapEv=G.Hd)();g.__ZN4shen15SetShowFaceMaskEb=a=>(g.__ZN4shen15SetShowFaceMaskEb=G.Id)(a);g.__ZN4shen15GetShowFaceMaskEv=()=>(g.__ZN4shen15GetShowFaceMaskEv=G.Jd)();g.__ZN4shen16SetShowBloodFlowEb=a=>(g.__ZN4shen16SetShowBloodFlowEb=G.Kd)(a);g.__ZN4shen16GetShowBloodFlowEv=()=>(g.__ZN4shen16GetShowBloodFlowEv=G.Ld)();g.__ZN4shen26SetEnableStartAfterSuccessEb=a=>(g.__ZN4shen26SetEnableStartAfterSuccessEb=G.Md)(a);
g.__ZN4shen26GetEnableStartAfterSuccessEv=()=>(g.__ZN4shen26GetEnableStartAfterSuccessEv=G.Nd)();g.__ZN4shen17SetHideShenaiLogoEb=a=>(g.__ZN4shen17SetHideShenaiLogoEb=G.Od)(a);g.__ZN4shen17GetHideShenaiLogoEv=()=>(g.__ZN4shen17GetHideShenaiLogoEv=G.Pd)();g.__ZN4shen33SetShowOutOfRangeResultIndicatorsEb=a=>(g.__ZN4shen33SetShowOutOfRangeResultIndicatorsEb=G.Qd)(a);g.__ZN4shen33GetShowOutOfRangeResultIndicatorsEv=()=>(g.__ZN4shen33GetShowOutOfRangeResultIndicatorsEv=G.Rd)();
g.__ZN4shen24SetShowTrialMetricLabelsEb=a=>(g.__ZN4shen24SetShowTrialMetricLabelsEb=G.Sd)(a);g.__ZN4shen24GetShowTrialMetricLabelsEv=()=>(g.__ZN4shen24GetShowTrialMetricLabelsEv=G.Td)();g.__ZN4shen17SetShowSignalTileEb=a=>(g.__ZN4shen17SetShowSignalTileEb=G.Ud)(a);g.__ZN4shen17GetShowSignalTileEv=()=>(g.__ZN4shen17GetShowSignalTileEv=G.Vd)();g.__ZN4shen29SetShowSignalQualityIndicatorEb=a=>(g.__ZN4shen29SetShowSignalQualityIndicatorEb=G.Wd)(a);
g.__ZN4shen29GetShowSignalQualityIndicatorEv=()=>(g.__ZN4shen29GetShowSignalQualityIndicatorEv=G.Xd)();g.__ZN4shen12GetFaceStateEv=()=>(g.__ZN4shen12GetFaceStateEv=G.Yd)();g.__ZN4shen21GetNormalizedFaceBboxEv=a=>(g.__ZN4shen21GetNormalizedFaceBboxEv=G.Zd)(a);g.__ZN4shen19GetMeasurementStateEv=()=>(g.__ZN4shen19GetMeasurementStateEv=G._d)();g.__ZN4shen32GetMeasurementProgressPercentageEv=()=>(g.__ZN4shen32GetMeasurementProgressPercentageEv=G.$d)();
g.__ZN4shen15GetHeartRate10sEv=a=>(g.__ZN4shen15GetHeartRate10sEv=G.ae)(a);g.__ZN4shen14GetHeartRate4sEv=a=>(g.__ZN4shen14GetHeartRate4sEv=G.be)(a);g.__ZN4shen20GetRealtimeHeartRateEv=a=>(g.__ZN4shen20GetRealtimeHeartRateEv=G.ce)(a);g.__ZN4shen18GetRealtimeHrvSdnnEv=a=>(g.__ZN4shen18GetRealtimeHrvSdnnEv=G.de)(a);g.__ZN4shen24GetRealtimeCardiacStressEv=a=>(g.__ZN4shen24GetRealtimeCardiacStressEv=G.ee)(a);g.__ZN4shen18GetRealtimeMetricsEf=(a,b)=>(g.__ZN4shen18GetRealtimeMetricsEf=G.fe)(a,b);
g.__ZN4shen21GetMeasurementResultsEv=a=>(g.__ZN4shen21GetMeasurementResultsEv=G.ge)(a);g.__ZN4shen28GetMeasurementResultsHistoryEv=a=>(g.__ZN4shen28GetMeasurementResultsHistoryEv=G.he)(a);g.__ZN4shen21GetHealthRisksFactorsEv=a=>(g.__ZN4shen21GetHealthRisksFactorsEv=G.ie)(a);g.__ZN4shen14GetHealthRisksEv=a=>(g.__ZN4shen14GetHealthRisksEv=G.je)(a);g.__ZN4shen18ComputeHealthRisksERKN2mx12health_risks12RisksFactorsE=(a,b)=>(g.__ZN4shen18ComputeHealthRisksERKN2mx12health_risks12RisksFactorsE=G.ke)(a,b);
g.__ZN4shen15GetMaximalRisksERKN2mx12health_risks12RisksFactorsE=(a,b)=>(g.__ZN4shen15GetMaximalRisksERKN2mx12health_risks12RisksFactorsE=G.le)(a,b);g.__ZN4shen15GetMinimalRisksERKN2mx12health_risks12RisksFactorsE=(a,b)=>(g.__ZN4shen15GetMinimalRisksERKN2mx12health_risks12RisksFactorsE=G.me)(a,b);g.__ZN4shen17GetReferenceRisksERKN2mx12health_risks12RisksFactorsE=(a,b)=>(g.__ZN4shen17GetReferenceRisksERKN2mx12health_risks12RisksFactorsE=G.ne)(a,b);
g.__ZN4shen21GetRealtimeHeartbeatsENSt3__28optionalIfEE=(a,b)=>(g.__ZN4shen21GetRealtimeHeartbeatsENSt3__28optionalIfEE=G.oe)(a,b);g.__ZN4shen11GetFacePoseEv=a=>(g.__ZN4shen11GetFacePoseEv=G.pe)(a);g.__ZN4shen19SetRecordingEnabledEb=a=>(g.__ZN4shen19SetRecordingEnabledEb=G.qe)(a);g.__ZN4shen19GetRecordingEnabledEv=()=>(g.__ZN4shen19GetRecordingEnabledEv=G.re)();g.__ZN4shen24GetTotalBadSignalSecondsEv=()=>(g.__ZN4shen24GetTotalBadSignalSecondsEv=G.se)();
g.__ZN4shen29GetCurrentSignalQualityMetricEv=()=>(g.__ZN4shen29GetCurrentSignalQualityMetricEv=G.te)();g.__ZN4shen22GetSignalQualityMapPngEv=a=>(g.__ZN4shen22GetSignalQualityMapPngEv=G.ue)(a);g.__ZN4shen17GetFaceTexturePngEv=a=>(g.__ZN4shen17GetFaceTexturePngEv=G.ve)(a);g.__ZN4shen25GetMetaPredictionImagePngEv=a=>(g.__ZN4shen25GetMetaPredictionImagePngEv=G.we)(a);g.__ZN4shen16GetFullPPGSignalEv=a=>(g.__ZN4shen16GetFullPPGSignalEv=G.xe)(a);g.__ZN4shen10GetTraceIDEv=a=>(g.__ZN4shen10GetTraceIDEv=G.ye)(a);
g.__ZN4shen16GetMeasurementIDEv=a=>(g.__ZN4shen16GetMeasurementIDEv=G.ze)(a);g.__ZN4shen11SetLanguageENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE=a=>(g.__ZN4shen11SetLanguageENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE=G.Ae)(a);g.__ZN4shen19GetSelectedLanguageEv=a=>(g.__ZN4shen19GetSelectedLanguageEv=G.Be)(a);g.__ZN4shen14GetPricingPlanEv=a=>(g.__ZN4shen14GetPricingPlanEv=G.Ce)(a);
g.__ZN4shen28GetEnableFullFrameProcessingEv=()=>(g.__ZN4shen28GetEnableFullFrameProcessingEv=G.De)();g.__ZN4shen28SetEnableFullFrameProcessingEb=a=>(g.__ZN4shen28SetEnableFullFrameProcessingEb=G.Ee)(a);g.__ZN4shen22GetEnableSummaryScreenEv=()=>(g.__ZN4shen22GetEnableSummaryScreenEv=G.Fe)();g.__ZN4shen22SetEnableSummaryScreenEb=a=>(g.__ZN4shen22SetEnableSummaryScreenEb=G.Ge)(a);g.__ZN4shen20GetEnableHealthRisksEv=()=>(g.__ZN4shen20GetEnableHealthRisksEv=G.He)();
g.__ZN4shen20SetEnableHealthRisksEb=a=>(g.__ZN4shen20SetEnableHealthRisksEb=G.Ie)(a);g.__ZN4shen17GetOnboardingModeEv=()=>(g.__ZN4shen17GetOnboardingModeEv=G.Je)();g.__ZN4shen17SetOnboardingModeENS_14OnboardingModeE=a=>(g.__ZN4shen17SetOnboardingModeENS_14OnboardingModeE=G.Ke)(a);g.__ZN4shen19GetCalibrationStateEv=()=>(g.__ZN4shen19GetCalibrationStateEv=G.Le)();g.__ZN4shen10GetVersionEv=a=>(g.__ZN4shen10GetVersionEv=G.Me)(a);
g.__ZN4shen18GetCalibrationDataEv=a=>(g.__ZN4shen18GetCalibrationDataEv=G.Ne)(a);g.__ZN4shen23GetSbpCalibrationOffsetEv=()=>(g.__ZN4shen23GetSbpCalibrationOffsetEv=G.Oe)();g.__ZN4shen23GetDbpCalibrationOffsetEv=()=>(g.__ZN4shen23GetDbpCalibrationOffsetEv=G.Pe)();var Ia=()=>(Ia=G.Qe)();g._handlePagehide=()=>(g._handlePagehide=G.Re)();var jj=g._main=(a,b)=>(jj=g._main=G.Se)(a,b),K=a=>(K=G.Te)(a);g._onVideoDevicesEnumerated=()=>(g._onVideoDevicesEnumerated=G.Ue)();
g._onVideoDevicesEnumerationError=()=>(g._onVideoDevicesEnumerationError=G.Ve)();g._onCameraInitialized=()=>(g._onCameraInitialized=G.We)();g._onCameraInitializationError=()=>(g._onCameraInitializationError=G.Xe)();g._ingestCameraFrame=(a,b,c,d,e,f,h,k,l)=>(g._ingestCameraFrame=G.Ye)(a,b,c,d,e,f,h,k,l);var I=a=>(I=G.Ze)(a);g._onBleDeviceReady=()=>(g._onBleDeviceReady=G._e)();g._onBleControlNotification=(a,b)=>(g._onBleControlNotification=G.$e)(a,b);
g._onBleDataNotification=(a,b)=>(g._onBleDataNotification=G.af)(a,b);var Af=a=>(Af=G.bf)(a),yf=()=>(yf=G.ef)(),Ka=(a,b,c,d,e,f)=>(Ka=G.ff)(a,b,c,d,e,f),Ra=()=>(Ra=G.gf)(),tf=(a,b,c,d,e)=>(tf=G.hf)(a,b,c,d,e),Ff=a=>(Ff=G.jf)(a),Nf=a=>(Nf=G.kf)(a),Vg=(a,b)=>(Vg=G.lf)(a,b),Hg=()=>(Hg=G.mf)(),Xa=()=>(Xa=G.nf)(),Kf=(a,b)=>(Kf=G.of)(a,b),uf=a=>(uf=G.pf)(a),sf=a=>(sf=G.qf)(a),rf=()=>(rf=G.rf)();g.ccall=dj;
g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>dj(a,b,c,f,d)};function kj(){if(0<Ta)Ua=kj;else if(m)aa(g),Sa();else{for(;0<mf.length;)mf.shift()(g);if(0<Ta)Ua=kj;else if(g.calledRun=!0,!ma){Sa();aa(g);var a=jj;try{var b=a(0,0);kd(b,!0)}catch(c){wf(c)}}}}kj();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
// When running as a pthread, construct a new instance on startup
isPthread && Module();
